puts "Creating Weapons..."
Weapon.create([
  { name: "Club", cost: 1, damage: "1d4 bludgeoning", weight: 2, properties: "Light" },
  { name: "Dagger", cost: 2, damage: "1d4 piercing", weight: 1, properties: "Finesse, light, thrown (range 20/60)" },
  { name: "Greatclub", cost: 2, damage: "1d8 bludgeoning", weight: 10, properties: "Two-handed" },
  { name: "Handaxe", cost: 5, damage: "1d6 slashing", weight: 2, properties: "Light, thrown (range 20/60)" },
  { name: "Javelin", cost: 1, damage: "1d6 piercing", weight: 2, properties: "Thrown (range 30/120)" },
  { name: "Light hammer", cost: 2, damage: "1d4 bludgeoning", weight: 2, properties: "Light, thrown (range 20/60)" },
  { name: "Mace", cost: 5, damage: "1d6 bludgeoning", weight: 4, properties: "-" },
  { name: "Quarterstaff", cost: 2, damage: "1d6 bludgeoning", weight: 4, properties: "Versatile (1d8)" },
  { name: "Sickle", cost: 1, damage: "1d4 slashing", weight: 2, properties: "Light" },
  { name: "Spear", cost: 1, damage: "1d6 piercing", weight: 3, properties: "Thrown, versatile (1d8)" },
  { name: "Unarmed strike", cost: 0, damage: "1 bludgeoning", weight: 0, properties: "-" },
  { name: "Crossbow, light", cost: 25, damage: "1d8 piercing", weight: 5, properties: "Ammunition (range 80/320), loading, two-handed" },
  { name: "Dart", cost: 0, damage: "1d4 piercing", weight: 0.25, properties: "Finesse, thrown (range 20/60)" },
  { name: "Shortbow", cost: 25, damage: "1d6 piercing", weight: 2, properties: "Ammunition (range 80/320), two-handed" },
  { name: "Sling", cost: 1, damage: "1d4 bludgeoning", weight: 0, properties: "Ammunition (range 30/120)" },
  { name: "Battleaxe", cost: 10, damage: "1d8 slashing", weight: 4, properties: "Versatile (1d10)" },
  { name: "Flail", cost: 10, damage: "1d8 bludgeoning", weight: 2, properties: "-" },
  { name: "Glaive", cost: 20, damage: "1d10 slashing", weight: 6, properties: "Heavy, reach, two-handed" },
  { name: "Greataxe", cost: 30, damage: "1d12 slashing", weight: 7, properties: "Heavy, two-handed" },
  { name: "Greatsword", cost: 50, damage: "2d6 slashing", weight: 6, properties: "Heavy, two-handed" },
  { name: "Halberd", cost: 20, damage: "1d10 slashing", weight: 6, properties: "Heavy, reach, two-handed" },
  { name: "Lance", cost: 10, damage: "1d12 piercing", weight: 6, properties: "Reach, special" },
  { name: "Longsword", cost: 15, damage: "1d8 slashing", weight: 3, properties: "Versatile (1d10)" },
  { name: "Maul", cost: 10, damage: "2d6 bludgeoning", weight: 10, properties: "Heavy, two-handed" },
  { name: "Morningstar", cost: 15, damage: "1d8 piercing", weight: 4, properties: "-" },
  { name: "Pike", cost: 5, damage: "1d10 piercing", weight: 18, properties: "Heavy, reach, two-handed" },
  { name: "Rapier", cost: 25, damage: "1d8 piercing", weight: 2, properties: "Finesse" },
  { name: "Scimitar", cost: 25, damage: "1d6 slashing", weight: 3, properties: "Finesse, light" },
  { name: "Shortsword", cost: 10, damage: "1d6 piercing", weight: 2, properties: "Finesse, light" },
  { name: "Trident", cost: 5, damage: "1d6 piercing", weight: 4, properties: "Thrown (20/60), versatile (1d8)" },
  { name: "War pick", cost: 5, damage: "1d8 piercing", weight: 2, properties: "-" },
  { name: "Warhammer", cost: 15, damage: "1d8 bludgeoning", weight: 2, properties: "Versatile (1d10)" },
  { name: "Whip", cost: 2, damage: "1d4 slashing", weight: 3, properties: "Finesse, reach" },
  { name: "Blowgun", cost: 10, damage: "1 piercing", weight: 1, properties: "Ammunition (range 25/100), loading" },
  { name: "Crossbow, hand", cost: 75, damage: "1d6 piercing", weight: 3, properties: "Ammunition (range 30/120), light, loading" },
  { name: "Crossbow, heavy", cost: 50, damage: "1d10 piercing", weight: 18, properties: "Ammunition (range 100/400), heavy, loading, two-handed" },
  { name: "Longbow", cost: 50, damage: "1d8 piercing", weight: 2, properties: "Ammunition (range 150/600), heavy, two-handed" },
  { name: "Net", cost: 1, damage: "-", weight: 3, properties: "Special, thrown (range 5/15)" }
])
puts "Weapons created: #{Weapon.count}"
