puts "Creating Categories..."
Category.create!([
  { name: "Ammunition", description: "You can shoot better and more with this", min_weight: 1, max_weight: 1 },
  { name: "Amulets", description: "You can look better and more with this", min_weight: 1, max_weight: 1 },
  { name: "Armor", description: "You can defend with this", min_weight: 20, max_weight: 80 },
  { name: "Artifacts", description: "You can make powerful things with this", min_weight: 1, max_weight: 10 },
  { name: "Books" , description: "You can make studies with this", min_weight: 1, max_weight: 6 },
  { name: "Boots" , description: "You can make discoveries with this", min_weight: 1, max_weight: 6 },
  { name: "Bracelet" , description: "You can cover your wrist with this", min_weight: 1, max_weight: 3 },
  { name: "Candle", description: "You can make light with this", min_weight: 1, max_weight: 5 },
  { name: "Cloak", description: "You can dress better with this", min_weight: 1, max_weight: 10 },
  { name: "Elixirs", description: "You can make magical things with this", min_weight: 1, max_weight: 3 },
  { name: "Food", description: "You can make hunger run away with this", min_weight: 1, max_weight: 10 },
  { name: "Gems", description: "You can make yourself rich with this", min_weight: 1, max_weight: 10 },
  { name: "Gloves", description: "You can grab things with this", min_weight: 1, max_weight: 5 },
  { name: "Helms", description: "You can make so many things with this", min_weight: 1, max_weight: 10 },
  { name: "Horns", description: "You can make noise with this", min_weight: 1, max_weight: 5 },
  { name: "Miscellaneous", description: "You can make anything with this", min_weight: 1, max_weight: 10 },
  { name: "Potent Ingredients", description: "You can make great things with this", min_weight: 1, max_weight: 5 },
  { name: "Potions", description: "You can make make things with this", min_weight: 1, max_weight: 5 },
  { name: "Rings", description: "You can look better and more with this", min_weight: 1, max_weight: 1 },
  { name: "Scrolls", description: "You can everything you dream with this", min_weight: 1, max_weight: 1 },
  { name: "Shields", description: "You can protect with this", min_weight: 5, max_weight: 15 },
  { name: "Staffs", description: "You can make attacks with this", min_weight: 1, max_weight: 10 },
  { name: "Tools", description: "You can make a lot of cool things with this", min_weight: 1, max_weight: 10 },
  { name: "Trinkets", description: "You can look awesome with this", min_weight: 1, max_weight: 10 },
  { name: "Wands", description: "You can make ranged attacks with this", min_weight: 2, max_weight: 5 },
  { name: "Weapons", description: "You can make attacks with this", min_weight: 1, max_weight: 10 },
])
puts "Categories created: #{Category.count}"
