# frozen_string_literal: true

# ══════════════════════════════════════════════════════════════
# MIDDLE-EARTH LORE MODULE — LEGACY CONSTANTS
# Used only by db/migrate/20260329150001_seed_lore_entries.rb
# to populate the lore_entries table. At runtime, all lore is
# read from the database via LoreEntry model.
# ══════════════════════════════════════════════════════════════
module MiddleEarthLore
  # ── Name-generation prefixes by rarity ──
  PREFIXES = {
    "Common"    => %w[Worn Sturdy Rustic Humble Simple Honest Faithful Tempered Battered Reliable Solid Modest Seasoned Trusty Homely],
    "Uncommon"  => %w[Elven Dwarven Númenórean Dúnadan Keen Blessed Gleaming Valiant Embered Ironforged Starlit Westron Gondorian Rohirric Silvered],
    "Rare"      => %w[Runed Enchanted Mystic Hallowed Moon-wrought Star-kindled Fëanorian Noldorin Sindarin Silvan Mithril-woven Dwimmer-crafted Spell-forged Gondolindrim Eregion-wrought],
    "Very Rare" => %w[Ainur-touched Void-wrought Eldar-forged Shadow-bane Silmaril-lit Valar-blessed Oromë-swift Aulë-tempered Ulmo-quenched Morgul-bane Undying Maiar-kindled Fëanor-inspired Celebrimbor-wrought Telchar-forged],
    "Legendary" => %w[Doom-spoken World-shaping Oath-bound Silmaril-blessed Noldor-crowned Valar-forged Doom-of-Mandos Morgoth-bane Ring-rival Flame-imperishable First-born Gondolin-wrought Undying-Lands Eärendil-blessed Fate-woven],
    "Ancestral" => %w[Primordial Ainulindalë-born Ilúvatar-willed Flame-imperishable Timeless Void-born Creation-sung World-founding Ea-shaping Music-born Thought-of-Ilúvatar Un-made First-conceived Eternal Boundless],
  }.freeze

  # ── Category-based name titles ──
  CATEGORY_TITLES = {
    "Weapons"    => %w[Blade Edge Fang Wrath Fury Bane Sting Cleaver Glamdring Grond Aeglos Gurthang Anglachel Orcrist],
    "Armor"      => %w[Bulwark Hauberk Corslet Ward Coat Panoply Mail Harness Byrnie Plate Aegis Mantle Shell],
    "Shields"    => %w[Wall Guardian Barrier Ward Buckler Defender Protector Aegis Bulwark Rampart Shield Targe Escutcheon],
    "Potions"    => %w[Draught Elixir Cordial Miruvor Athelas Ent-draught Lembas-water Tincture Essence Distillation Infusion Flask Brew],
    "Scrolls"    => %w[Codex Tome Script Decree Rune Glyph Tengwar Cirth Writ Grimoire Folio Testament Chronicle],
    "Rings"      => %w[Band Circle Ring Seal Vilya Narya Nenya Annulus Coil Signet Loop Crown Cipher],
    "Amulets"    => %w[Talisman Pendant Jewel Silmaril Evenstar Elfstone Nauglamír Elessar Locket Token Wardstone Phylactery],
    "Wands"      => %w[Rod Scepter Staff Wand Conduit Channeler Beacon Implement Spark Focus Catalyst Baton],
    "Staffs"     => %w[Staff Pillar Spire Rod Crook Scepter Stave Mace Monolith Column Obelisk Crozier],
    "Boots"      => %w[Treads Striders Walkers Greaves Steps Runners Sabatons Trackers Pathfinders Wanderers Sojourners Wayfarers],
    "Gloves"     => %w[Grasp Clutch Grip Gauntlets Mitts Fists Vambraces Bracers Hands Touch Talons Fingers],
    "Helms"      => %w[Crown Helm Casque Crest Diadem Dragon-helm Visor Circlet Coronet Tiara Sallet Pinnacle],
    "Cloaks"     => %w[Shroud Mantle Veil Cape Cloak Shadow Wrap Lórien-cloth Raiment Vestment Cowl Pall],
    "Books"      => %w[Grimoire Lexicon Codex Chronicle Thain's-Book Red-Book Palimpsest Almanac Volume Libram Compendium Folio],
    "Gems"       => %w[Silmaril Shard Crystal Jewel Stone Heart Arkenstone Elessar Phial Prism Geode Mote],
    "Ammunition" => %w[Bolt Arrow Dart Quarrel Shot Shaft Spike Needle Missile Slug Round],
    "Bracelet"   => %w[Bangle Cuff Chain Torc Armlet Circlet Shackle Link Fetter Coil Band],
    "Trinkets"   => %w[Curio Relic Token Keepsake Heirloom Bauble Memento Oddity Fetish Charm Icon],
  }.freeze

  # ── Suffixes: Middle-earth locations, figures, events ──
  SUFFIXES = [
    # Elven realms & cities
    "of Gondolin", "of Nargothrond", "of Doriath", "of Menegroth",
    "of Rivendell", "of Lothlórien", "of the Grey Havens", "of Eregion",
    "of Lindon", "of Tirion upon Túna", "of Alqualondë", "of Formenos",
    "of the Falas", "of Ossiriand", "of Tol Eressëa", "of Caras Galadhon",
    # Dwarven strongholds
    "of Khazad-dûm", "of Erebor", "of Nogrod", "of Belegost",
    "of the Iron Hills", "of Aglarond", "of the Glittering Caves",
    "of Tumunzahar", "of Gabilgathol", "of Hadhodrond",
    # Númenor & Gondor
    "of Númenor", "of Armenelos", "of Minas Tirith", "of Osgiliath",
    "of Minas Ithil", "of Annúminas", "of Fornost", "of Dol Amroth",
    "of Pelargir", "of Gondor", "of Arnor",
    # Rohan & the North
    "of Edoras", "of Helm's Deep", "of the Riddermark",
    "of Bree", "of the Shire", "of Isengard",
    # Dark places
    "of Angband", "of Thangorodrim", "of Barad-dûr", "of Mordor",
    "of Dol Guldur", "of Minas Morgul", "of Utumno",
    # Valinor
    "of Valinor", "of Aman", "of Taniquetil", "of the Undying Lands",
    "of the Blessed Realm", "of Mandos", "of Aulë's Forge",
    # Valar & Maiar
    "of Manwë's Breath", "of Ulmo's Depths", "of Aulë's Fire",
    "of Yavanna's Song", "of Varda's Stars", "of Oromë's Hunt",
    "of Nienna's Tears", "of Mandos's Doom", "of Tulkas's Wrath",
    "of Lúthien's Grace", "of Eärendil's Light",
    # Events & ages
    "of the First Age", "of the Elder Days", "of the Years of the Trees",
    "of the War of Wrath", "of the Last Alliance", "of the Nirnaeth Arnoediad",
    "of the Fall of Gondolin", "of the Dagor Bragollach",
    "of the Darkening of Valinor", "of the War of the Ring",
    "of the Kinslaying", "of the Flight of the Noldor",
    # Abstract / epic
    "of the Firstborn", "of the Secondborn", "of the Free Peoples",
    "of Shadow and Flame", "of Starlight", "of the Deathless Lands",
    "of the Sundering Seas", "of the Straight Road",
    "of the Long Defeat", "of the Uttermost West",
  ].freeze

  SIMPLE_SUFFIXES = [
    "of Power", "of Might", "of Valor", "of Grace", "of Wrath",
    "of Wisdom", "of Starlight", "of Shadow", "of Flame", "of Doom",
    "of the West", "of the North", "of the Eldar", "of the Dwarves",
    "of the Dúnedain", "of Twilight", "of Dawn", "of Mithril", "of Stars",
    "of the Mark",
  ].freeze

  # ══════════════════════════════════════════════════════
  # DESCRIPTION LORE — Deep Middle-earth
  # ══════════════════════════════════════════════════════

  LEGENDARY_SMITHS = [
    # Valar & Maiar
    "Aulë the Smith, Maker of the Dwarves and greatest craftsman among the Valar",
    "Sauron, when he was yet Mairon the Admirable, before his corruption by Morgoth",
    "Curumo (Saruman), whose skill with ring-lore and metal was surpassed only by his ambition",
    # Noldorin Elves
    "Fëanor, greatest of the Noldor, whose hands wrought the Silmarils themselves",
    "Celebrimbor, grandson of Fëanor and lord of the Gwaith-i-Mírdain of Eregion",
    "Curufin the Crafty, fifth son of Fëanor, who inherited much of his father's skill",
    "Mahtan, the great Noldorin smith who taught Fëanor the secrets of metalwork",
    "the smiths of the Gwaith-i-Mírdain, the Jewel-smiths of Eregion",
    "Eöl the Dark Elf of Nan Elmoth, who forged Anglachel and Anguirel from a fallen star",
    "Pengolodh the Wise of Gondolin, loremaster and craftsman of the Hidden City",
    # Dwarves
    "Telchar of Nogrod, greatest of Dwarf-smiths, who forged Narsil and Angrist",
    "Gamil Zirak, master smith of Nogrod and teacher of Telchar",
    "Narvi, the Dwarf-craftsman who wrought the Doors of Durin with Celebrimbor",
    "the smiths of Erebor, heirs to the craft traditions of Durin's Folk",
    "the Longbeard forgemasters of Khazad-dûm in its years of glory",
    "the weaponsmiths of Nogrod, famed throughout Beleriand for their steel",
    "the armorsmiths of Belegost who fashioned the Dragon-helm of Dor-lómin",
    "Thorin Oakenshield's own armorers, working in the reclaimed halls of Erebor",
    # Men
    "the Númenórean weapon-wrights of Armenelos, whose art rivaled the Eldar",
    "the master smiths of Westernesse in the days of Tar-Minastir",
    "the Dúnedain craftsmen of Annúminas, before the fall of the North-kingdom",
    "the armorsmiths of Gondor in the days of its greatest strength",
    "a nameless smith of the Edain in the service of King Thingol of Doriath",
    # Gondolin specialists
    "the artificers of Gondolin, working in secret forges beneath Amon Gwareth",
    "Rog, lord of the House of the Hammer of Wrath in Gondolin",
    "the craftsmen of the House of the Golden Flower in the Hidden City",
  ].freeze

  LEGENDARY_WIELDERS = [
    # First Age heroes
    "Fingolfin, High King of the Noldor, who dueled Morgoth before the gates of Angband",
    "Fëanor, Spirit of Fire, mightiest of the Children of Ilúvatar",
    "Fingon the Valiant, who rescued Maedhros from Thangorodrim",
    "Turgon, King of Gondolin, the Hidden City",
    "Beren Erchamion, who cut a Silmaril from Morgoth's iron crown",
    "Lúthien Tinúviel, fairest of all the Children of Ilúvatar",
    "Túrin Turambar, the tragic hero who slew Glaurung the dragon",
    "Húrin Thalion, the Steadfast, who stood alone against Morgoth's armies",
    "Ecthelion of the Fountain, who slew Gothmog Lord of Balrogs",
    "Glorfindel of the House of the Golden Flower, who slew a Balrog in the Fall of Gondolin",
    "Eärendil the Mariner, bearer of the Silmaril and hope of Elves and Men",
    "Thingol Greycloak, King of Doriath and lord of the Sindar",
    "Maedhros the Tall, eldest son of Fëanor",
    "Maglor the Singer, whose voice was the fairest in all the world",
    "Beleg Cúthalion, greatest archer among the Elves of Doriath",
    # Second Age
    "Gil-galad, last High King of the Noldor in Middle-earth, who bore the spear Aeglos",
    "Elendil the Tall, who founded the realms of Arnor and Gondor",
    "Isildur, who cut the One Ring from Sauron's hand",
    "Anárion, defender of Minas Anor against Sauron's forces",
    "Elrond Half-elven, Herald of Gil-galad and lord of Rivendell",
    "Círdan the Shipwright, oldest of the Elves in Middle-earth",
    # Third Age
    "Gandalf the Grey, who became Gandalf the White, wielder of Glamdring and bearer of Narya",
    "Aragorn, son of Arathorn, heir of Isildur, who bore Andúril Flame of the West",
    "Théoden King of Rohan, who rode to glory at the Pelennor Fields",
    "Éowyn, shieldmaiden of Rohan, who slew the Witch-king of Angmar",
    "Éomer, Third Marshal of the Riddermark and later King of Rohan",
    "Boromir, Captain of the White Tower, who fell defending the Halflings",
    "Faramir, Captain of the Rangers of Ithilien",
    "Legolas Greenleaf of the Woodland Realm",
    "Gimli, son of Glóin, Elf-friend and Lord of Aglarond",
    "Thorin Oakenshield, King under the Mountain",
    "Bilbo Baggins, who bore Sting into the darkness of Mirkwood",
    "Frodo Baggins, Ring-bearer, who carried the One Ring to Mount Doom",
    "Samwise Gamgee, the truest of all companions, who bore the Phial of Galadriel",
    "Prince Imrahil of Dol Amroth, whose line bore Elven blood",
    "the Witch-king of Angmar, Lord of the Nazgûl",
  ].freeze

  LEGENDARY_PLACES = [
    # Valinor
    "the forge-halls of Aulë beneath Taniquetil in Valinor",
    "Fëanor's workshop in Tirion upon Túna, where the Silmarils were wrought",
    "the halls of Mahtan in Valinor, where the art of metalwork was perfected",
    "the Gardens of Lórien in Valinor, where dreams take form",
    # First Age Beleriand
    "the hidden forges of Gondolin beneath Amon Gwareth, the Hill of Watch",
    "Menegroth, the Thousand Caves of King Thingol in Doriath",
    "the great smithies of Nogrod in the Blue Mountains",
    "the halls of Belegost, where the finest Dwarf-mail was wrought",
    "Nargothrond, the great underground fortress of Finrod Felagund",
    "the smithies of the Falas, where Círdan's people wrought ships and steel",
    "the hidden vale of Tumladen, where Gondolin the Beautiful stood",
    "Himring, the fortress of Maedhros, cold hill upon the March of Maedhros",
    "the forge of Eöl in the dark woods of Nan Elmoth",
    # Second Age
    "the Gwaith-i-Mírdain's workshops in Ost-in-Edhil, chief city of Eregion",
    "the Sammath Naur, the Chambers of Fire within Orodruin where the One Ring was forged",
    "the armories of Númenor in Armenelos the Golden",
    "Khazad-dûm in the days of Durin, when mithril flowed like water",
    "the Tower of Avallónë on Tol Eressëa, where the Palantíri were made",
    # Third Age
    "the forges of Erebor, the Lonely Mountain, reclaimed by Thorin's company",
    "Rivendell, the Last Homely House, where Andúril was reforged from the shards of Narsil",
    "the workshops of Isengard before Saruman's fall to darkness",
    "the deep halls of Aglarond, the Glittering Caves of Helm's Deep",
    "the armories of Minas Tirith in the days of its greatest strength",
    "the smithies of Dale, rebuilt after the fall of Smaug",
    "the Prancing Pony in Bree, where many a tale is told and many a relic changes hands",
    "a hidden forge in the depths of the Misty Mountains, long forgotten",
    "the ruins of Annúminas beside Lake Evendim",
    "the ancient dwarf-holds beneath the Grey Mountains",
    "Dol Amroth, the castle by the sea, where Gondorian and Elven craft mingled",
  ].freeze

  LEGENDARY_EVENTS = [
    # Years of the Trees & First Age
    "the Darkening of Valinor, when Morgoth and Ungoliant destroyed the Two Trees",
    "the Flight of the Noldor from Valinor and the dreadful Kinslaying at Alqualondë",
    "the Dagor-nuin-Giliath, the Battle under Stars, first battle of the Noldor in Middle-earth",
    "the Dagor Aglareb, the Glorious Battle that established the Siege of Angband",
    "the Dagor Bragollach, the Battle of Sudden Flame that broke the Siege of Angband",
    "the Nirnaeth Arnoediad, the Battle of Unnumbered Tears, greatest disaster of the Eldar",
    "the Fall of Gondolin, when Morgoth's hosts destroyed the fairest city of the Elves",
    "the Fall of Nargothrond, brought low by the cunning of Glaurung the dragon",
    "the Fall of Doriath, when Dwarves and Elves shed blood over the Nauglamír and a Silmaril",
    "the Quest of Beren and Lúthien for the Silmaril from Morgoth's crown",
    "Fingolfin's single combat with Morgoth at the gates of Angband",
    "the slaying of Glaurung by Túrin Turambar at the ravine of Cabed-en-Aras",
    "the War of Wrath, when the Valar overthrew Morgoth and Beleriand was broken",
    "the Oath of Fëanor and his sons, which drove the doom of the Noldor",
    "Eärendil's voyage to Valinor, bearing the Silmaril, to plead for aid against Morgoth",
    # Second Age
    "the forging of the Rings of Power in Eregion by Celebrimbor and the disguised Sauron",
    "the forging of the One Ring by Sauron in the fires of Mount Doom",
    "the War of the Elves and Sauron, which laid waste to Eregion",
    "the Downfall of Númenor, when the Blessed Realm was removed from the circles of the world",
    "the founding of Gondor and Arnor by Elendil and his sons",
    "the War of the Last Alliance of Elves and Men against Sauron",
    "the Battle of Dagorlad and the seven-year siege of Barad-dûr",
    "the death of Gil-galad and Elendil on the slopes of Orodruin",
    # Third Age
    "the Battle of the Five Armies before the gates of Erebor",
    "the fall of Khazad-dûm when the Dwarves awoke Durin's Bane",
    "the War of the Ring, when the free peoples made their last stand against Sauron",
    "the Battle of the Pelennor Fields, greatest battle of the Third Age",
    "the Battle of the Hornburg at Helm's Deep",
    "the destruction of the One Ring in the fires of Mount Doom",
    "the fall of Gandalf the Grey in Khazad-dûm and his return as the White",
    "the siege of Minas Tirith by the armies of Mordor",
    "Éowyn's slaying of the Witch-king upon the Pelennor Fields",
    "the charge of the Rohirrim at dawn upon the Pelennor",
  ].freeze

  # ── Valar, Maiar, and Powers (equivalent to DEITIES) ──
  DEITIES = [
    "Ilúvatar, the One, Creator of all",
    "Manwë Súlimo, King of the Valar, Lord of the Breath of Arda",
    "Varda Elentári, Queen of the Stars, whom the Elves call Elbereth Gilthoniel",
    "Ulmo, Lord of Waters, who dwells alone in the deeps of the Outer Sea",
    "Aulë the Smith, maker of mountains and metals, who created the Dwarves",
    "Yavanna Kementári, Queen of the Earth, giver of fruits and growing things",
    "Mandos (Námo), the Doomsman of the Valar, keeper of the Houses of the Dead",
    "Vairë the Weaver, who weaves the story of the world in her tapestries",
    "Nienna, who mourns for the marring of Arda, from whose tears wisdom is born",
    "Oromë the Great, the Huntsman of the Valar, who first found the Elves",
    "Tulkas Astaldo, the Champion of Valinor, strongest of all in deeds of prowess",
    "Nessa the Dancer, swift as an arrow, whose joy is in running and dance",
    "Estë the Gentle, healer of hurts and of weariness",
    "Lórien (Irmo), master of visions and dreams, who tends the Gardens of Lórien in Valinor",
    "Morgoth Bauglir, the Dark Enemy, once Melkor mightiest of the Ainur",
    "Sauron the Deceiver, the Dark Lord, once a Maia of Aulë",
    "Gandalf (Olórin), wisest of the Maiar, who walked among the Elves unseen",
    "Saruman (Curumo), once head of the Istari, whose knowledge of ring-craft was great",
    "Radagast the Brown, friend of birds and beasts",
    "the Balrogs, Maiar corrupted by Morgoth into spirits of fire and shadow",
    "Tom Bombadil, Eldest, whose true nature none can say",
    "Goldberry, the River-daughter",
    "Ungoliant, the primordial darkness in spider form, whose hunger was never sated",
  ].freeze

  # ── Organizations & peoples ──
  ORGANIZATIONS = [
    "the Noldor, the Deep Elves, mightiest of the Eldar in lore and craft",
    "the Sindar, the Grey Elves of Beleriand under King Thingol",
    "the Silvan Elves of Lothlórien under Galadriel and Celeborn",
    "the Wood-elves of the Woodland Realm under King Thranduil",
    "Durin's Folk, the Longbeards, eldest and greatest of the Dwarf-kindreds",
    "the Firebeards and Broadbeams of Nogrod and Belegost",
    "the Dúnedain of the North, Rangers and heirs of Arnor",
    "the Dúnedain of the South, lords of Gondor",
    "the Rohirrim, the Horse-lords of the Riddermark",
    "the Istari, the five Wizards sent by the Valar to contest Sauron",
    "the White Council, led by Saruman and later Gandalf, who opposed the Shadow",
    "the House of Fëanor, bound by their terrible Oath",
    "the House of Fingolfin, who endured the crossing of the Helcaraxë",
    "the Gwaith-i-Mírdain, the Jewel-smiths of Eregion",
    "the Ents of Fangorn, shepherds of the trees since the Elder Days",
    "the Eagles of Manwë, led by Thorondor and later Gwaihir",
    "the Beornings, skin-changers of the Vales of Anduin",
    "the faithful Númenóreans, the Elendili, who defied Sauron and Ar-Pharazôn",
    "the Grey Company, Dúnedain who rode with Aragorn to the Paths of the Dead",
    "the Fellowship of the Ring, the Nine Walkers sent from Rivendell",
    "the Galadhrim, the tree-people of Lothlórien",
    "the Nazgûl, the Nine Ring-wraiths, enslaved kings of Men",
    "the Guard of the Citadel of Minas Tirith",
    "the Corsairs of Umbar, descendants of the King's Men of Númenor",
  ].freeze

  # ── Exotic materials ──
  EXOTIC_MATERIALS = [
    "mithril, the true-silver of Khazad-dûm, most precious of metals, light as silk and hard as dragon-scales",
    "galvorn, the dark metal devised by Eöl in Nan Elmoth, black and shining as jet",
    "ithildin, the star-moon substance that glows only by starlight or moonlight, wrought by the Noldor",
    "the black iron of Angband, forged in Morgoth's pits beneath Thangorodrim",
    "silima, the crystalline substance invented by Fëanor, harder than diamond, from which the Silmarils were made",
    "a fallen star of Aulë's making, sky-iron found still warm upon the earth",
    "mallorn-wood from the trees of Lothlórien, golden and imperishable",
    "lebethron, the beloved wood of the woodwrights of Gondor",
    "laen, the volcanic glass wrought by Dwarf-smiths into blades as hard as steel",
    "tilkal, the ancient alloy of six metals spoken of in the oldest tales",
    "the white stone of Minas Tirith, quarried from the Mountains of Shadow before Sauron's return",
    "steel tempered in dragon-fire, quenched in the icy waters of Celebrant",
    "a splinter of Grond, the great mace of Morgoth, the Hammer of the Underworld",
    "a fragment of the Silmaril-light caught in crystal during the Darkening of Valinor",
    "iron from the ruin of Thangorodrim, twisted by the power of a fallen Vala",
    "elanor-gold, metal refined from the golden flowers of Lothlórien by Galadhrim craftsmen",
    "Westernesse steel, forged in Númenor with arts now lost to mortal Men",
    "dwarf-steel from the deep forges of Erebor, folded a hundred times in Durin's tradition",
    "silver from the mines of Celebdil, blessed by the presence of the Mirrormere",
    "athelas-infused bronze, wrought by the healers of Gondor for items of restoration",
    "bark of the White Tree of Gondor, preserved since the days of Nimloth",
    "a shard of the Elessar, the Elfstone of Eärendil, green as the living earth",
    "obsidian from the slopes of Orodruin, still warm with the fires of Mount Doom",
    "ice from the Helcaraxë, the Grinding Ice, that never melts even in the hottest forge",
  ].freeze

  AGES_AND_ERAS = [
    "the Time before Time, when only Ilúvatar and the Ainur existed in the Void",
    "the Ainulindalë, the Great Music by which Arda was conceived",
    "the Years of the Lamps, when Arda was lit by Illuin and Ormal",
    "the Years of the Trees, when the light of Telperion and Laurelin illuminated Valinor",
    "the First Age of the Sun, the Elder Days of Beleriand's wars against Morgoth",
    "the years of the Siege of Angband, when the Noldor held Morgoth at bay (F.A. 60–455)",
    "the years after the Dagor Bragollach (F.A. 455), when the Siege was broken",
    "the Second Age, when the Rings of Power were forged and Númenor rose and fell",
    "the height of Númenor's power (S.A. 600–3255), when its ships ruled every sea",
    "the years of Eregion's glory (S.A. 750–1697), when Elves and Dwarves worked in friendship",
    "the forging of the Rings of Power (S.A. 1500–1590) by the Gwaith-i-Mírdain",
    "the Third Age, from the defeat of Sauron at the Last Alliance to the destruction of the One Ring",
    "the years of Gondor's greatest might (T.A. 1–1050), when the South-kingdom flourished",
    "the Long Winter (T.A. 2758–2759) and the years of hardship that followed",
    "the years of the Watchful Peace (T.A. 2063–2460), when Sauron withdrew from Dol Guldur",
    "the Quest of Erebor (T.A. 2941), when Thorin's company reclaimed the Lonely Mountain",
    "the War of the Ring (T.A. 3018–3019), the final struggle against Sauron",
  ].freeze

  CURSES_AND_QUIRKS = [
    "it is said that the shadow of Morgoth's malice falls upon all who covet it, though those who receive it freely find it a faithful servant",
    "once each age it vanishes from the hands of its keeper, as though summoned by Mandos himself, only to appear again where it is most needed",
    "prolonged possession kindles in the bearer's eyes a faint Elven-light, the afterglow of the Trees that once lit the world",
    "this item is said to have a twin, wrought in the same forge in the same hour, and the two sing a chord when brought near each other",
    "it will not suffer the hand of an Orc or servant of the Shadow — it becomes burning cold to the touch of the wicked",
    "on occasion it whispers in Quenya, the High Speech of the Noldor, words that none now living fully comprehend",
    "those who die bearing it are said to find swifter passage through the Halls of Mandos, as though the item vouches for them",
    "it is warm to the touch of Elf-friends and cold as the Helcaraxë to all others",
    "the palantíri cannot perceive it — its existence is veiled from the Seeing Stones as though it were never made",
    "on nights when Eärendil's star burns brightest it weighs nothing, and on moonless nights twice as much, as though the Silmaril in the sky has a claim upon it",
    "anyone who bears it for more than a day begins to understand Sindarin, even if they have never heard the Elven-tongue spoken",
    "it carries the faint scent of athelas — kingsfoil — and wherever it rests, the air smells of spring after rain",
    "Elven-sight reveals traces of the old script of Fëanor upon it, runes that tell a story different to each reader",
    "if broken, it mends itself slowly, drawing on the ambient light of sun and stars — the process takes seven days and seven nights",
    "it is invisible to the servants of Sauron, passing through their awareness like a whisper in a storm",
    "songbirds gather near it, and in Lothlórien the nightingales sing more sweetly in its presence",
    "it hums with a deep, resonant note when brought near other objects of power, as though greeting kindred spirits",
  ].freeze

  PROPHECIES = [
    "The ancient prophecy of Mandos speaks of such an item: 'When the world is broken and remade, this shall endure; for it was made with love, and love alone outlasts the Long Defeat.'",
    "In the Red Book of Westmarch, a passage in Bilbo's own hand describes a relic matching its description: 'It seemed to me a thing of great age and greater purpose, and I dared not keep it long.'",
    "The Dúnedain Rangers preserve an oral tradition about 'the burden that lightens': an artifact that grows easier to bear the more just its wielder's cause.",
    "Galadriel's Mirror once showed a vision of this item in the hands of a figure standing alone before a great darkness — whether past or future, the Lady would not say.",
    "Elrond spoke of it at the Council, though his words were not recorded in the common account: 'I have seen its like before, in an age when such things were more common — and more dangerous.'",
    "The Palantír of Orthanc, when wrested from Saruman's influence, showed a brief vision of this item resting upon a stone table in a place of great light. Gandalf refused to interpret the vision.",
    "A verse in the Lay of Leithian, in Bilbo's translation, may refer to it: 'Forged in fire, quenched in tears / it shall outlast the fleeting years / and when the Shadow falls once more / be beacon bright on darkened shore.'",
    "The Ents of Fangorn speak of a 'hard-thing-that-remembers' in their slow language — Treebeard acknowledged it might be this item, but said he would need a very long time to be certain.",
  ].freeze

  # ── Origins per rarity ──
  ORIGINS = {
    "Common" => [
      "Forged by a village smith in the lands of Bree, from honest iron and simple craft.",
      "Made by a Hobbit tinker in the workshops of Michel Delving, sturdy and practical.",
      "Crafted by a journeyman smith in the lower circles of Minas Tirith.",
      "Produced in the workshops of Dale, following the craft traditions restored after Smaug's fall.",
      "Fashioned during a long winter in a Dúnedain camp, from what materials were at hand.",
      "Purchased from a peddler on the East-West Road, its origins unknown but its quality sound.",
      "Wrought by an apprentice of the Erebor forges — functional, reliable, a credit to Dwarf teaching.",
      "Made by the Men of Rohan, sturdy as the horses they ride and twice as dependable.",
      "Assembled from salvaged materials after a skirmish with Orcs along the Misty Mountains.",
      "Crafted by a Gondorian smith of the third circle, skilled but not yet a master.",
      "Fashioned in Lake-town, where the craft of Men is practical and trade-worthy.",
      "Forged in the smithies of Belegost's diminished remnant in the Blue Mountains, plain but well-made.",
    ],
    "Uncommon" => [
      "Forged under a Hunter's Moon by an Elven smith of the Grey Havens, the work of a single night's inspiration.",
      "Discovered in a troll-hoard in the Trollshaws, alongside other spoils of forgotten travelers.",
      "Created by a Dúnedain Ranger who wove fragments of old Westernesse craft into its making.",
      "Blessed by an Elf-lord in exchange for aid during the crossing of the Misty Mountains.",
      "Recovered from the hoard of a young dragon in the Withered Heath.",
      "Won in the Battle of Five Armies and carried south by a victorious warrior of Dale.",
      "Found in the ruins of Annúminas by a Ranger who recognized its quality.",
      "Commissioned by the steward of Dol Amroth as a gift for a loyal knight.",
      "Imbued with minor enchantments by a Wizard of lesser order, one of the Blue Istari's students.",
      "Traded by a Dwarf-merchant of the Iron Hills who swore it was forged in old Erebor — for once, the merchant told the truth.",
      "Crafted in Rivendell as an exercise in Noldorin technique; the student's work surpassed expectations.",
      "Found among the possessions of a fallen warrior of Gondor in the ruins of Osgiliath.",
      "Enchanted by an Elven-smith of Mirkwood with subtle woodcraft spells woven into the metal.",
      "Recovered from a Corsair ship captured off the coast of Belfalas.",
      "Discovered among the grave-goods of a barrow in the Barrow-downs, purified by Tom Bombadil himself.",
    ],
    "Rare" => [
      "Forged in rivalry between two Dwarf-clans of Erebor, each striving to outdo the other's craft.",
      "Drawn from the dreams of an Elven-lord who slept beneath the eaves of Lothlórien for a year and a day.",
      "Crafted by Dwarven runesmiths in the deep chambers of Khazad-dûm, quenched in the cold waters of the Mirrormere.",
      "Recovered from the tomb of a Dúnedain chieftain whose sword-arm defended Arnor for forty years.",
      "Imbued with power during a rare conjunction of Eärendil's star and the moon.",
      "Salvaged from the wreckage of a Númenórean ship found beneath the waters of the Bay of Belfalas.",
      "Forged by %{smith} during a three-day labor guided by visions of the Blessed Realm.",
      "Discovered in a vein of mithril in the Mines of Moria, shaped as if by nature itself over uncounted years.",
      "Enchanted in the workshops of Eregion in the brief years of peace before Sauron's war.",
      "Created from %{material}, worked by %{smith} under the light of Ithil on Midsummer's Eve.",
      "Recovered from the ruins of a Númenórean outpost in the south, its enchantments preserved across millennia.",
      "Forged during %{era} and passed through many hands before vanishing from all records — until now.",
      "Found in a sealed chamber beneath Erebor, alongside a journal in Cirth runes describing its creation.",
      "Crafted at the request of a mortal who won a riddle-contest with a Dragon.",
      "Woven with Elven enchantment by a circle of Galadhrim, shaped over a full year under the mallorn trees.",
      "Pulled from the clutches of a stone-troll in the Ettenmoors, still gripping it after centuries of petrifaction.",
    ],
    "Very Rare" => [
      "Forged from star-iron that fell upon Arda in the First Age, still carrying the cold fire of the firmament. The metal remembers the void between the stars.",
      "Drawn from a barrow of the First Age by an Elf who walked the paths of the dead and returned unchanged. The item still carries the chill of that passage.",
      "Created during the War of Wrath, when the Valar broke Thangorodrim and the earth itself was remade. Its maker sacrificed their craft-hand to complete the work.",
      "Assembled from fragments of three ancient relics, each broken in a different age. The echoes of their former power hum within this new form.",
      "Born from the last ember of one of the Two Trees of Valinor, caught in crystal before the light faded forever from the world.",
      "Shaped by %{smith} in %{place}, where the boundary between Middle-earth and the Undying Lands grows thin as gossamer. Echoes of the Blessed Realm cling to it still.",
      "This relic was the prize of %{event}. %{wielder} claimed it from the ruin, though some say it chose its bearer rather than the other way around.",
      "Grown — not forged — in the gardens of Lothlórien, where Galadriel's power causes metal to bloom like elanor and gems to ripen on crystal vines. The process took seven mortal lifetimes.",
      "Forged in the deeps of Erebor using techniques passed down from Durin the Deathless himself. The fire of that ancient tradition burns within it.",
      "Created from %{material}, shaped during %{event} by %{smith}. It carries the memory of that day like a scar — or a rune of power.",
      "Recovered from the ruin of Dol Guldur after the White Council drove out the Necromancer. What dark arts had been worked upon it, none could say — but its original virtue endured.",
      "Pulled from the fabric of Arda itself by a Maia who gave it physical form through an act of will that diminished them forever.",
      "Crafted beneath the waves of the Great Sea in a Telerin workshop that survived the Downfall of Númenor by being already underwater.",
      "Wrought during a conjunction of all visible stars by the last of the Noldorin smiths of Lindon, each component blessed by a different star's light.",
      "Forged in dragonfire — willingly given by one of the great wyrms — and cooled in the sacred springs of Ithilien. The dragon's name is inscribed in Cirth upon the hilt, though no one dares speak it.",
    ],
    "Legendary" => [
      "Forged in dragonfire by the last smith of Gondolin before the city fell, this artifact was meant to be a weapon against Morgoth himself. When Gondolin was destroyed, it was carried out by a survivor of the House of the Golden Flower. Kingdoms of Elves and Men have risen and fallen in the ages since, but this endures.",
      "Legend holds that a Vala walked Middle-earth in disguise and, moved by an act of extraordinary selflessness, left this behind as a gift. Those who have carried it speak of hearing whispers of guidance in the Elvish tongue during their darkest hours.",
      "This artifact was the final work of %{smith}, who spent forty years gathering materials from across Middle-earth and beyond. Upon completing it, they sailed West to Valinor. Some say the item consumed their art; others believe they departed knowing their work in Middle-earth was done.",
      "Wrought from wood of the White Tree and steel of Westernesse, this item has witnessed the rise and fall of every kingdom of Men since Númenor. Its surface bears the marks of countless battles, each one a chapter in the story of the Free Peoples.",
      "Created during %{event}, when the fate of Middle-earth hung in the balance. %{wielder} bore it as one chosen by destiny to stand against the Shadow. It absorbed power with each blow struck in that great conflict.",
      "Recovered from %{place} by %{wielder}, who spent years navigating deadly perils and ancient guardians. The quest cost the lives of many companions. The survivor emerged changed — bound to the artifact by something deeper than mere possession.",
      "Seven Elven-lords pooled their fëa — their spiritual essence — to create this artifact during %{event}. Each diminished themselves in the making, their memories and wisdom crystallized within the enchantment. The item sometimes speaks with their voices.",
      "This item was present when Sauron forged the One Ring in the Sammath Naur, and it absorbed a fragment of power as the Dark Lord's malice poured into his creation. The Ring wanted to corrupt it. It refused. Gandalf himself examined it and spoke only one word: 'Remarkable.'",
      "Forged by Aulë the Smith in the deeps of time and gifted to the eldest of the Dwarves. It passed through every great Dwarven kingdom — Khazad-dûm, Nogrod, Belegost, Erebor — before fate scattered it to the winds. Dwarves who see it weep, though they cannot explain why.",
      "Created by Celebrimbor himself, greatest of the Gwaith-i-Mírdain, in the years before Sauron revealed his treachery. It was hidden before Eregion fell and thus was never tainted by the Dark Lord's influence. The Three Rings are counted the greatest of the Elven-rings, but this was made with the same art.",
      "This artifact surfaced in %{place} after %{event}. %{wielder} bore it for a time, but ultimately surrendered it, writing in a letter preserved in Rivendell: 'It has done what it came to do through me. I am merely the latest in a chain that stretches back to the Elder Days.'",
      "Wrought from %{material} by %{smith} during %{era}. The creation required the willing gift of an Elf's immortal life, whose fëa was woven into the metal. On quiet nights, the item radiates a gentle warmth — the last echo of an Elven soul's compassion.",
    ],
    "Ancestral" => [
      "This artifact predates the Sun and Moon. It was wrought in the Years of the Trees, when the light of Telperion and Laurelin illuminated Valinor, and it still carries that light within it. Those who hold it see, for a fleeting instant, the world as it was before Morgoth marred it — green and golden and impossibly beautiful. The grief of that vision has broken the minds of lesser beings.",
      "Woven from the Music of the Ainur by Ilúvatar himself and placed in Arda as a thread of the Great Theme, this item was not created so much as it was always meant to exist. Every prophecy of the Eldar references it obliquely, and every great turning point in the history of Middle-earth can be traced back to its influence. It does not merely have a destiny; it IS destiny made tangible.",
      "Born in the Timeless Halls before Arda was made, forged from the Flame Imperishable that Ilúvatar alone can wield. When the Ainur sang the world into being, this item crystallized from the first chord of the Great Music — the moment creation became reality. Fëanor himself beheld it once and wept, for even the Silmarils were lesser works.",
      "The oldest beings in Arda — Círdan the Shipwright, Tom Bombadil, Treebeard — all remember a time when this item was already ancient. It carries within it the memory of the Void before Eä was spoken, the silence before the Music began. To wield it is to hold infinity in your hand.",
      "Created at the moment Ilúvatar spoke 'Eä!' and the world came into being, this artifact is simultaneously the first and last work of creation. Time bends in its presence. Heroes who have borne it describe experiencing the entire span of Arda's history in a single breath, from the Ainulindalë to the Dagor Dagorath that will end the world.",
      "The concept of this artifact exists in the thought of Ilúvatar, and therefore in every reality that could ever be. The Ainur sang it into being without knowing they did so, and Morgoth himself could not unmake it — for to destroy it would be to unravel the Theme of Ilúvatar, and not even the mightiest of the Valar can do that.",
      "This item was made in the Timeless Halls, where Ilúvatar dwells beyond the world. It passed through the Void into Arda at the singing of the Great Music, and it has been present at every great event since — the lighting of the Two Trees, the creation of the Silmarils, the forging of the Rings, the Downfall of Númenor, and the destruction of the One Ring. It is always there, at the hinge of fate, waiting.",
      "When Morgoth wove his discord into the Great Music, Ilúvatar turned even that evil to greater purpose. This item is the physical manifestation of that turning — darkness transmuted into something stronger than either good or evil alone. The Valar cannot fully comprehend it. Sauron feared it. Gandalf, alone among the wise, understood it — and he smiled.",
      "Fëanor, in the days of his greatness, once held this item and set it down without speaking. His sons asked what he had seen. 'The work of one greater than I,' he said — and Fëanor called no one his superior. It is the only recorded instance of Fëanor acknowledging a craft beyond his own.",
      "This artifact was old when Ungoliant devoured the Trees. It was ancient when Morgoth first descended into Arda. It was primordial when the Ainur first sang. It exists because Ilúvatar thought of it, and what Ilúvatar conceives cannot be unmade. The Noldor have a name for it in the High Speech: *Ainasúrë*, the Breath of the Holy Ones.",
      "The Red Book of Westmarch, in a passage attributed to Gandalf himself, contains this cryptic entry: 'There are things in Middle-earth older than Sauron, older than the Elves, older than the stones. This is one of them. It was not made — it always was. And when the world is unmade at the Last Battle, it will remain, for it belongs not to this world but to the One who imagined it.'",
    ],
  }.freeze

  # ── Effect descriptions — Middle-earth flavored ──
  EFFECT_DESCRIPTIONS = {
    "Attack Bonus" => [
      "guides strikes with the uncanny precision of an Elven warrior trained since the Years of the Trees",
      "hones the wielder's combat instincts as keen as Beleg Cúthalion's bow-arm — strikes land where mortal eyes cannot follow",
      "bends fate to favor deadly accuracy, as though the hand of Tulkas himself guides the blow",
      "whispers in the ancient battle-tongue of the Noldor, adjusting the wielder's form with each swing",
      "channels the battle-wisdom of the Eldar who fought Morgoth in the First Age, each stroke guided by millennia of war-craft",
      "strikes with the precision of Fingolfin before the gates of Angband, finding every weakness in the enemy's guard",
    ],
    "Attack Damage" => [
      "amplifies the destructive force of every blow, striking with the fury of Grond, the Hammer of the Underworld",
      "channels the elemental wrath of Ulmo's waves — the very air screams on impact",
      "tears through defenses as Anglachel tore through Glaurung's iron belly",
      "unleashes concussive bursts of force that echo like the fall of Thangorodrim",
      "strikes with the fury of a Balrog's whip, the impact rippling outward in waves of shadow and flame",
      "delivers blows that resonate through body and spirit alike, as the swords of the Noldor once did against the servants of Morgoth",
    ],
    "Defense" => [
      "creates an invisible barrier that deflects harm, shimmering like the Girdle of Melian",
      "hardens the air around the bearer into a ward as impenetrable as the walls of Gondolin",
      "absorbs the force of attacks before they land, dispersing the energy as starlight",
      "projects a lattice of protective runes in the Tengwar of the Noldor that flare when danger approaches",
      "surrounds the bearer in a shield of power like the defenses woven by the Elven-rings",
      "weaves a defense drawn from the same art that raised the Hidden City — a wall no enemy can see until they strike it",
    ],
    "Healing" => [
      "mends wounds with golden light that carries the fragrance of athelas, the kingsfoil",
      "accelerates the body's natural recovery, knitting flesh and bone as the hands of a true King of Gondor",
      "draws on the living force of Arda itself, the life that Yavanna breathed into growing things",
      "pulses with a heartbeat-rhythm that eases pain as Estë the Gentle eases weariness in the Gardens of Lórien",
      "channels the healing art of the Eldar, whose medicine surpasses mortal understanding",
      "heals with the same restorative power as the waters of the Mirrormere or the springs of Ithilien",
    ],
    "Material" => [
      "is wrought from a substance that defies understanding — lighter than mithril yet harder than the iron of Angband",
      "incorporates materials from beyond Middle-earth, their properties shifting with the phases of Ithil",
      "resonates with the inherent power of its exotic components, each gathered from a different corner of Arda",
      "was crafted from ore that fell from the sky, a star-fragment still carrying the cold fire of Varda's making",
      "is fashioned from %{material}, a substance that even the Noldorin loremasters struggle to classify",
      "bears the unmistakable hallmarks of Dwarf-craft — light as mithril, hard as the roots of the mountains",
    ],
    "Stealth" => [
      "bends light and shadow around the bearer, granting the invisibility of an Elven-cloak of Lórien",
      "wraps the wearer in silence and secrecy — even the keen ears of Elves lose the trail",
      "makes the bearer nearly imperceptible, like a Hobbit moving through the woods: unseen, unheard, barely there",
      "absorbs all sound and presence into an envelope of absolute stillness, as the Elves pass through the world unseen",
      "grants the shadow-craft of the Rangers of Ithilien, who moved as ghosts beneath the eaves of Mordor",
      "cloaks the wearer as thoroughly as the One Ring concealed its bearer — without the terrible cost",
    ],
    "Speed" => [
      "quickens the bearer's movements to a blur — swift as Oromë's steed Nahar across the plains of Valinor",
      "grants speed as though gravity were merely a suggestion, each stride covering the ground of three",
      "bestows preternatural swiftness that could outpace the arrows of the Galadhrim",
      "bends time slightly around the bearer, granting that extra heartbeat the Eldar use to slip between moments",
      "channels the speed of Shadowfax, lord of all horses, letting the bearer move as fast as thought",
      "grants the swiftness of the Eagles of Manwë, blurring between strides as though carried on the wind",
    ],
    "Protection" => [
      "wards against threats mortal and sorcerous, turning aside blade and dark magic with equal ease",
      "projects an aura of safety like the protection of the Elven-rings — danger simply forgets the bearer exists",
      "shields the bearer with ancient protective sigils in the Tengwar of Fëanor, each guarding against a different peril",
      "creates a sanctuary of peace within chaos, like the Hidden Valley of Rivendell where evil cannot easily enter",
      "radiates the protective blessing of Ulmo, Lord of Waters, whose care for the Children of Ilúvatar never wavered",
      "invokes the same art of concealment that hid Gondolin for centuries from the eyes of Morgoth",
    ],
    "Resistance" => [
      "fortifies the bearer against hostile forces, turning lethal power into mild discomfort",
      "renders the wearer resilient as the Dwarves whom Aulë made to endure, shrugging off what would break lesser folk",
      "provides enduring protection that learns from each assault, as a shield-wall of the Dúnedain adapts to every foe",
      "grants the legendary endurance of Húrin Thalion, who stood alone and unyielding against the hosts of Morgoth",
      "shields the bearer as completely as a wall of the Hornburg — steadfast and immovable",
    ],
    "Conjuration" => [
      "opens brief doorways through the fabric of Arda, through which glimpses of distant lands flash",
      "bends space as the Istari could, summoning what is needed from far away",
      "draws things through the unseen paths of Middle-earth, as messages travel by ways unknown to mortals",
      "rips holes in distance with the precision of the Palantíri, connecting two points across the width of the world",
      "draws upon the same power that opens the Doors of Durin — speak 'friend' and enter",
    ],
    "Flight" => [
      "grants the gift of flight, carried on wings of force as the Eagles of Manwë bear the worthy aloft",
      "defies the pull of the earth at the bearer's command, as naturally as the Elves walk upon snow",
      "lifts the wearer on currents of power, trailing motes of starlight like Eärendil across the heavens",
      "bestows flight as swift and sure as Thorondor, King of Eagles, whose wingspan shadowed the peaks of Thangorodrim",
      "harnesses the winds of Manwë, granting freedom of the skies that only the Great Eagles have known",
    ],
    "Frosting" => [
      "radiates bitter cold, as though the ice of the Helcaraxë still remembers the crossing of the Noldor",
      "sheaths itself in frost that never melts, cold as the peaks of the Misty Mountains in deepest winter",
      "can freeze the very air to ice, creating walls and bridges of crystal at the bearer's will",
      "channels the eternal winter of Forochel, the bitter cold of the far north where the Witch-king's realm once lay",
      "radiates the deathly cold of the Grinding Ice — the kind of cold that swallowed an army of Elves and left no trace",
    ],
    "Lightning" => [
      "crackles with the fury of a storm summoned by Manwë, Lord of the Winds",
      "calls down bolts of lightning as Gandalf once called flame upon the mountainside",
      "channels the raw power of thunder, arcing between enemies with devastating precision",
      "thunders with the voice of Oromë's great horn Valaróma, each discharge a tempest unleashed",
      "stores the lightning of the great storms that break upon Taniquetil, discharging it with the wrath of the Elder King",
    ],
    "Vision" => [
      "reveals what is hidden, as the Mirror of Galadriel shows things that were, things that are, and things that yet may be",
      "grants perception that pierces all disguise and darkness, as Elven-sight sees the unseen world",
      "opens the bearer's eyes to truths beyond mortal understanding; some report seeing the threads of fate that the Valar weave",
      "bestows sight as keen as the Palantíri, the Seeing Stones of Númenor — far-reaching and ever-watchful",
      "grants truesight sharper than the gaze of Sauron's Eye, piercing every veil and shadow",
    ],
    "Luck" => [
      "subtly tilts fortune in the bearer's favor, as the hidden purposes of Ilúvatar guide all things to their appointed end",
      "seems to attract fortunate happenings: doors left open, enemies looking the wrong way, storms clearing at the perfect moment",
      "bends probability as Gandalf would say: 'There are other forces at work in this world besides the will of evil'",
      "carries the peculiar luck of Hobbits — that inexplicable talent for being in exactly the right place at the right time",
      "radiates the kind of impossible fortune that brought Bilbo to Gollum's cave and the Ring to Frodo's hand",
    ],
    "Control" => [
      "grants dominion over the will of others, as the Rings of Power bound the Nine Kings of Men",
      "allows the wielder to sway minds, though unlike Sauron's art, it compels through persuasion rather than domination",
      "exerts an authority that few can resist — the commanding presence of one born to rule, like Aragorn before the Black Gate",
      "wields the power of command as the Istari do: not by force, but by a wisdom that makes obedience seem natural",
      "channels the voice of authority as Gandalf spoke to Théoden, breaking the spell of lesser wills",
    ],
    "Minding" => [
      "resonates with the thoughts of those nearby, as Galadriel could read the hearts of the Fellowship",
      "expands the bearer's awareness far beyond mortal limits, touching minds as the Eldar commune without words",
      "creates a bond between the wielder and the world, as the Ents know the thoughts of trees and stone",
      "opens the bearer's mind to the deep currents of thought that flow through Middle-earth like underground rivers",
      "connects the wielder to the unspoken knowledge of Arda, as Gandalf perceived truths hidden from lesser minds",
    ],
    "Summoning" => [
      "calls forth loyal servants, bound by ancient oaths sworn in the Elder Days",
      "summons allies as Gandalf summoned the Eagles — creatures come willingly, drawn by the artifact's authority",
      "opens channels to distant allies; those who answer speak of the item with reverence, as though it were a banner of old",
      "draws aid as a great horn draws warriors to battle — the call of Boromir's horn at Amon Hen, magnified a hundredfold",
      "commands the loyalty of beast and being through ancient bonds older than the Secondborn",
    ],
    "Enhance" => [
      "amplifies the bearer's natural gifts beyond mortal limits — a warrior becomes as the Eldar, a sage as the Istari",
      "infuses body and mind with surges of power that sharpen every sense and multiply every strength",
      "pushes every capability to its peak and beyond; the experience is described as briefly touching the power of the Ainur",
      "grants an enhancement like the might of the Dúnedain of old, whose lifespan and strength surpassed common Men",
      "elevates the bearer to the edge of what mortals can achieve — the boundary between Men and the Firstborn",
    ],
    "Utility" => [
      "provides a versatile array of useful enchantments that adapt to the bearer's need",
      "adapts to serve whatever the moment demands — as Gandalf always had the right tool, the right word, the right fire",
      "contains a wellspring of practical magic, each enchantment awakening intuitively when needed",
      "offers the kind of resourceful magic the Grey Pilgrim favored — subtle, practical, and endlessly useful",
      "functions with the ingenious precision of Dwarf-craft, solving problems its maker never imagined",
    ],
    "Understanding" => [
      "bridges all tongues and forms of speech, from the High Speech of the Noldor to the slow language of the Ents",
      "opens the mind to comprehend every written and spoken word, from ancient Quenya to the Black Speech of Mordor",
      "grants intuitive understanding beyond mere translation — the bearer reads intent, truth, and heart as Galadriel does",
      "bestows the gift of tongues as the Istari possessed it, making every language as familiar as the Common Speech",
    ],
    "Absortion" => [
      "hungrily devours hostile magic, as Ungoliant devoured the light of the Trees",
      "converts incoming power into stored energy, growing brighter with each spell it drinks",
      "creates a void that swallows enchantments as Shelob's darkness swallowed the light of Eärendil's star — though this serves a nobler purpose",
      "absorbs magic with the insatiable hunger of a Silmaril gathering light — every hostile spell feeds its reserves",
      "drinks in power as parched earth drinks rain, turning the enemy's greatest weapon into the bearer's greatest strength",
    ],
    "Saving Throws" => [
      "bolsters the bearer's will and endurance as the Dúnedain endure — unbowed by age, unbroken by hardship",
      "provides the mental fortitude of one who has looked upon the Silmarils and remained sane",
    ],
    "Initiative" => [
      "sharpens reflexes to Elven swiftness — the bearer acts before danger can materialize",
      "grants the battle-awareness of Glorfindel reborn — the bearer moves first, always, as one who has already seen death",
    ],
    "Inmunity" => [
      "grants absolute protection against specific harm, as mithril turns aside blade and dart",
      "renders the bearer utterly impervious, as a Balrog is immune to common flame",
    ],
  }.freeze

  PERSONALITY_TRAITS = [
    "It hums a fragment of an Elvish song when danger approaches, the pitch rising as the threat draws near.",
    "It grows warm to the touch during moments of great emotion, as if sharing in its bearer's joy or grief.",
    "Those who carry it dream of places they have never seen — the shores of Valinor, the towers of Gondolin, the gardens of Lórien.",
    "It seems to resist being set aside, growing subtly heavier when put down, as if it fears being lost again.",
    "It glows with a faint Elven-light in the presence of Orcs, the light carrying the silver of Telperion.",
    "Animals react to it with awe — horses bow their heads, birds land on the bearer's shoulder, and wolves slink away.",
    "It smells faintly of athelas after being used, a fragrance that eases weariness and lifts the heart.",
    "Those nearby occasionally hear the distant sound of Elven singing, though no Elf walks within a hundred leagues.",
    "It trails faint motes of starlight when moved quickly, like the wake of Eärendil across the sky.",
    "Flowers bloom more swiftly in its presence, turning to face it as the mallorn trees turn toward Valinor.",
    "Its weight changes with the phases of the moon — featherlight under Ithil's full face, heavier in the dark of the moon.",
    "It occasionally whispers fragments of Quenya, the High Speech of the Noldor, as though remembering conversations from another age.",
    "Water near it becomes pure and sweet, and food consumed in its presence sustains twice as long, like Lembas.",
    "It casts a shadow unlike its own shape — the shadow of something grander, as though it remembers a greater form.",
    "Flames lean toward it as campfires lean toward the Elves, and hearths burn longer in its proximity.",
    "The Tengwar inscribed upon it shift and rearrange when none observe, telling a different tale each time they are read.",
    "Compasses spin erratically near it, their needles ultimately pointing toward the West — always toward the West.",
    "The bearer's reflection in still water appears wearing armor of an ancient style, as if showing a previous bearer.",
    "Touching it for the first time triggers a vivid flash of memory — not the bearer's own, but a fragment of an Elder Day.",
    "It resonates with a deep note during thunderstorms, answering the voice of Manwë across the sky.",
    "Elven-sight reveals it burning far brighter than it should — like a captured star, compressed into mortal form.",
    "It sings a barely audible chord when brought near other objects of power, as instruments harmonize in an orchestra.",
    "The air around it is always comfortable, regardless of weather — a small echo of the Blessed Realm's eternal spring.",
    "Those who hold it long develop an instinctive sense of direction, always knowing the way West toward the Sea.",
    "It leaves a faint afterimage, as though reality needs a moment to remember where it is.",
    "Growing things flourish in its presence — grass grows greener, flowers open, and dead wood puts forth new leaves.",
    "In complete darkness it emits just enough light to see by — the exact amount needed, no more, no less.",
    "The bearer develops an inexplicable longing for the Sea, the same yearning the Elves call the 'Sea-longing.'",
    "Zones of corrupted magic — the influence of Mordor, of barrow-wights — calm in its presence, as sunlight burns away fog.",
    "It hums a unique melody for each person who touches it, as though it remembers a song composed for their soul alone.",
  ].freeze

  DRAMATIC_CLOSINGS = [
    "Many have sought to possess it; few have proven worthy. The rest were forgotten by history — and by the item.",
    "Its true potential, the wise warn, has yet to be fully awakened — and what will happen when it does may reshape Middle-earth.",
    "Those who wield it speak of a burden heavier than the item's weight, for it demands as much as it gives — as all great things do.",
    "It is said that the item chooses its bearer, as Gandalf said of the Ring: 'It was not Gollum, but the Ring itself that decided things.'",
    "Legends claim it will be carried at the Dagor Dagorath, the Last Battle at the end of the world, when Morgoth returns from the Void.",
    "Every age produces a hero destined to carry it — and a servant of darkness destined to covet it. The cycle has never been broken.",
    "Its story is far from over. If anything, as Gandalf might say, the tale has only just begun.",
    "Some believe destroying it would unmake a part of Arda itself. Others believe that is precisely why it must one day be destroyed.",
    "The last three bearers perished within a year of claiming it. Whether by fate, curse, or willing sacrifice, the Wise do not say.",
    "When the bearer sleeps, the item dreams for them — showing visions of the Elder Days, of the world's making, and of what may yet come to pass.",
    "Gandalf held it once, briefly, and set it down with the words: 'Not for me. My task is otherwise.'",
    "Elrond has recorded it in the annals of Rivendell with the same notation given to the Rings of Power: 'Handle with the utmost care.'",
    "The keepers of the Red Book have dedicated a separate volume to accounts of this item. It is kept in a locked case in the Thain's study.",
    "Those who have wielded it and survived — precious few — describe the experience as 'hearing the Music of the Ainur and knowing your part in it.'",
    "In the end, it will outlast its bearer, as it has outlasted every bearer since the Elder Days. It is patient. It endures. It waits for the one who is meant to carry it last.",
    "Sauron once sought it. He failed. That alone should tell you everything you need to know about its power.",
  ].freeze

  EFFECT_TRANSITIONS = [
    "Its most remarkable property is that it",
    "Those who have studied it in the libraries of Rivendell note that it",
    "Beyond its physical form, it",
    "In battle, it",
    "When called upon, it",
    "More wondrous still, it",
    "Its enchantment ensures that it",
    "In the hands of a worthy bearer, it",
    "Perhaps most notably, it",
    "As if that were not enough, it also",
    "Veterans of the great wars who have borne it confirm that it",
    "The loremasters of Rivendell have documented that it",
    "Rangers of the Dúnedain who have carried it report that it",
    "According to those who have witnessed it wielded in anger, it",
    "What truly sets it apart from lesser works is that it",
  ].freeze

  HISTORICAL_ANECDOTES = [
    "It once saved the life of %{wielder} during %{event}, turning a certain doom into an improbable victory.",
    "Records in the library of Rivendell mention it by a different name in each Age, as though it reinvents itself.",
    "%{wielder} bore it for many years before passing it on, saying simply: 'Its work through me is done.'",
    "A guild of thieves in Bree once placed a bounty on it — the contract was never fulfilled, and the guild no longer exists.",
    "It was thought lost during %{event}, but resurfaced decades later in the possession of a Hobbit who said they found it 'just lying about, as if waiting.'",
    "Three kingdoms of Men have listed it among their crown treasures, though it has never rested in any vault for long.",
    "Gandalf examined it and said only: 'Be careful with that. It is older than it looks, and it looks very old indeed.'",
    "During %{event}, it is said to have acted of its own will, protecting its bearer from a blow they never saw.",
    "%{wielder} used it to survive the Battle of Five Armies, when other arms shattered against the Orc-host.",
    "It was last seen in %{place} before %{event}, after which it vanished from the annals of the Wise for three hundred years.",
    "%{organization} tracked its movements across Middle-earth for decades with obsessive care.",
    "Bilbo wrote a verse about it in Rivendell, but Gandalf asked that it be removed from the final manuscript. The argument lasted a week.",
    "The Dúnedain attempted to secure it during %{event}, but %{wielder} had already vanished into the Wild.",
    "It passed through the markets of Dale seven times in a single day before vanishing with a traveler heading East.",
    "During the siege of Erebor, %{wielder} used it to hold the gate against a hundred Orcs — a deed the Dwarves still sing of.",
    "A sorcerer of the East attempted to study its enchantments and was found the next morning alive but unable to work any magic at all.",
    "%{wielder} brought it to %{place}, where it resonated with the ancient power of that land so strongly that the very stones hummed.",
    "It was offered as tribute to Smaug the Golden. The dragon examined it, returned it, and told the trembling ambassador: 'Keep it. I have no use for things I cannot eat — but you may.'",
  ].freeze
end
