puts "Destroying all..."
Category.destroy_all
Rarity.destroy_all
Effect.destroy_all
Item.destroy_all
ItemEffect.destroy_all

puts "Creating Weapons..."
Weapon.create([
  { name: "Club", cost: 1, damage: "1d4 bludgeoning", weight: 2, properties: "Light" },
  { name: "Dagger", cost: 2, damage: "1d4 piercing", weight: 1, properties: "Finesse, light, thrown (range 20/60)" },
  { name: "Greatclub", cost: 2, damage: "1d8 bludgeoning", weight: 10, properties: "Two-handed" },
  { name: "Handaxe", cost: 5, damage: "1d6 slashing", weight: 2, properties: "Light, thrown (range 20/60)" },
  { name: "Javelin", cost: 1, damage: "1d6 piercing", weight: 2, properties: "Thrown (range 30/120)" },
  { name: "Light hammer", cost: 2, damage: "1d4 bludgeoning", weight: 2, properties: "Light, thrown (range 20/60)" },
  { name: "Mace", cost: 5, damage: "1d6 bludgeoning", weight: 4, properties: "-" },
  { name: "Quarterstaff", cost: 2, damage: "1d6 bludgeoning", weight: 4, properties: "Versatile (1d8)" },
  { name: "Sickle", cost: 1, damage: "1d4 slashing", weight: 2, properties: "Light" },
  { name: "Spear", cost: 1, damage: "1d6 piercing", weight: 3, properties: "Thrown, versatile (1d8)" },
  { name: "Unarmed strike", cost: 0, damage: "1 bludgeoning", weight: 0, properties: "-" },
  { name: "Crossbow, light", cost: 25, damage: "1d8 piercing", weight: 5, properties: "Ammunition (range 80/320), loading, two-handed" },
  { name: "Dart", cost: 0, damage: "1d4 piercing", weight: 0.25, properties: "Finesse, thrown (range 20/60)" },
  { name: "Shortbow", cost: 25, damage: "1d6 piercing", weight: 2, properties: "Ammunition (range 80/320), two-handed" },
  { name: "Sling", cost: 1, damage: "1d4 bludgeoning", weight: 0, properties: "Ammunition (range 30/120)" },
  { name: "Battleaxe", cost: 10, damage: "1d8 slashing", weight: 4, properties: "Versatile (1d10)" },
  { name: "Flail", cost: 10, damage: "1d8 bludgeoning", weight: 2, properties: "-" },
  { name: "Glaive", cost: 20, damage: "1d10 slashing", weight: 6, properties: "Heavy, reach, two-handed" },
  { name: "Greataxe", cost: 30, damage: "1d12 slashing", weight: 7, properties: "Heavy, two-handed" },
  { name: "Greatsword", cost: 50, damage: "2d6 slashing", weight: 6, properties: "Heavy, two-handed" },
  { name: "Halberd", cost: 20, damage: "1d10 slashing", weight: 6, properties: "Heavy, reach, two-handed" },
  { name: "Lance", cost: 10, damage: "1d12 piercing", weight: 6, properties: "Reach, special" },
  { name: "Longsword", cost: 15, damage: "1d8 slashing", weight: 3, properties: "Versatile (1d10)" },
  { name: "Maul", cost: 10, damage: "2d6 bludgeoning", weight: 10, properties: "Heavy, two-handed" },
  { name: "Morningstar", cost: 15, damage: "1d8 piercing", weight: 4, properties: "-" },
  { name: "Pike", cost: 5, damage: "1d10 piercing", weight: 18, properties: "Heavy, reach, two-handed" },
  { name: "Rapier", cost: 25, damage: "1d8 piercing", weight: 2, properties: "Finesse" },
  { name: "Scimitar", cost: 25, damage: "1d6 slashing", weight: 3, properties: "Finesse, light" },
  { name: "Shortsword", cost: 10, damage: "1d6 piercing", weight: 2, properties: "Finesse, light" },
  { name: "Trident", cost: 5, damage: "1d6 piercing", weight: 4, properties: "Thrown (20/60), versatile (1d8)" },
  { name: "War pick", cost: 5, damage: "1d8 piercing", weight: 2, properties: "-" },
  { name: "Warhammer", cost: 15, damage: "1d8 bludgeoning", weight: 2, properties: "Versatile (1d10)" },
  { name: "Whip", cost: 2, damage: "1d4 slashing", weight: 3, properties: "Finesse, reach" },
  { name: "Blowgun", cost: 10, damage: "1 piercing", weight: 1, properties: "Ammunition (range 25/100), loading" },
  { name: "Crossbow, hand", cost: 75, damage: "1d6 piercing", weight: 3, properties: "Ammunition (range 30/120), light, loading" },
  { name: "Crossbow, heavy", cost: 50, damage: "1d10 piercing", weight: 18, properties: "Ammunition (range 100/400), heavy, loading, two-handed" },
  { name: "Longbow", cost: 50, damage: "1d8 piercing", weight: 2, properties: "Ammunition (range 150/600), heavy, two-handed" },
  { name: "Net", cost: 1, damage: "-", weight: 3, properties: "Special, thrown (range 5/15)" }
])


puts "Creating Categories..."
Category.create!([
	{ name: "Ammunition", description: "You can shoot better and more with this", min_weight: 1, max_weight: 1 },
  { name: "Amulets", description: "You can look better and more with this", min_weight: 1, max_weight: 1 },
  { name: "Armor", description: "You can defend with this", min_weight: 20, max_weight: 80 },
  { name: "Artifacts", description: "You can make powerful things with this", min_weight: 1, max_weight: 10 },
  { name: "Boots" , description: "You can make discoveries with this", min_weight: 1, max_weight: 10 },
  { name: "Candle", description: "You can make light with this", min_weight: 1, max_weight: 5 },
  { name: "Cloak", description: "You can dress better with this", min_weight: 1, max_weight: 10 },
  { name: "Elixirs", description: "You can make magical things with this", min_weight: 1, max_weight: 3 },
  { name: "Food", description: "You can make hunger run away with this", min_weight: 1, max_weight: 10 },
  { name: "Gems", description: "You can make yourself rich with this", min_weight: 1, max_weight: 10 },
  { name: "Gloves", description: "You can grab things with this", min_weight: 1, max_weight: 5 },
  { name: "Helms", description: "You can make so many things with this", min_weight: 1, max_weight: 10 },
  { name: "Horns", description: "You can make noise with this", min_weight: 1, max_weight: 5 },
  { name: "Miscellaneous", description: "You can make anything with this", min_weight: 1, max_weight: 10 },
  { name: "Potent Ingredients", description: "You can make great things with this", min_weight: 1, max_weight: 5 },
  { name: "Potions", description: "You can make make things with this", min_weight: 1, max_weight: 5 },
  { name: "Rings", description: "You can look better and more with this", min_weight: 1, max_weight: 1 },
  { name: "Scrolls", description: "You can everything you dream with this", min_weight: 1, max_weight: 1 },
  { name: "Shields", description: "You can protect with this", min_weight: 5, max_weight: 15 },
  { name: "Staffs", description: "You can make attacks with this", min_weight: 1, max_weight: 10 },
  { name: "Tools", description: "You can make a lot of cool things with this", min_weight: 1, max_weight: 10 },
  { name: "Trinkets", description: "You can look awesome with this", min_weight: 1, max_weight: 10 },
  { name: "Wands", description: "You can make ranged attacks with this", min_weight: 2, max_weight: 5 },
  { name: "Weapons", description: "You can make attacks with this", min_weight: 1, max_weight: 10 },
])

puts "Creating Rarities..."
Rarity.create!([
	{ name: "Common", min_price: 1, max_price: 200, min_power: 0, max_power: 1 },
  { name: "Uncommon", min_price: 200, max_price: 500, min_power: 2, max_power: 2 },
  { name: "Rare", min_price: 500, max_price: 2000, min_power: 3, max_power: 4 },
  { name: "Very Rare", min_price: 2000, max_price: 7500, min_power: 5, max_power: 6 },
  { name: "Legendary", min_price: 7500, max_price: 30000, min_power: 7, max_power: 8 },
  { name: "Ancestral", min_price: 30000, max_price: 100000, min_power: 9, max_power: 10 },
])

puts "Creating Effects..."
weapon_category = Category.find_by(name: "Weapons")
armor_category = Category.find_by(name: "Armor")
ammunition_category = Category.find_by(name: "Ammunition")
amulet_category = Category.find_by(name: "Amulets")
ring_category = Category.find_by(name: "Rings")
shield_category = Category.find_by(name: "Shields")
gem_category = Category.find_by(name: "Gems")
cloak_category = Category.find_by(name: "Cloak")
boots_category = Category.find_by(name: "Boots")
wands_category = Category.find_by(name: "Wands")
trinkets_category = Category.find_by(name: "Trinkets")
gloves_category = Category.find_by(name: "Gloves")
potions_category = Category.find_by(name: "Potions")
helm_category = Category.find_by(name: "Helms")
staff_category = Category.find_by(name: "Staffs")

Effect.create!([
	{ name: "Attack +1", effect_type: "Attack Bonus", power_level: 1, description: "Your attack and damage rolls add +1", categories: [weapon_category, gloves_category] },
	{ name: "Attack +2", effect_type: "Attack Bonus", power_level: 2, description: "Your attack and damage rolls add +2", categories: [weapon_category, gloves_category] },
	{ name: "Attack +3", effect_type: "Attack Bonus", power_level: 3, description: "Your attack and damage rolls add +3", categories: [weapon_category] },
	{ name: "Attack +4", effect_type: "Attack Bonus", power_level: 4, description: "Your attack and damage rolls add +4", categories: [weapon_category] },
	{ name: "Attack +5", effect_type: "Attack Bonus", power_level: 5, description: "Your attack and damage rolls add +5", categories: [weapon_category] },
  { name: "Minor Luck", effect_type: "Attack Bonus", power_level: 2, description: "Allows to get 10 instead of rolling the d20 for an attack roll (3/day)", categories: [weapon_category, gloves_category] },

  { name: "Mithril Alloy", effect_type: "Material", power_level: 3, description: "Damage magical criatures, +1 to Attack, +1 to Damage, +1 to AC, +1 to Initiative Rolls, cannot be destroyed", categories: [weapon_category, armor_category, shield_category] },
  { name: "Mithril", effect_type: "Material", power_level: 5, description: "Damage magical criatures, +3 to Attack, +3 to Damage, +3 to AC, +3 to Initiative Rolls, cannot be destroyed", categories: [weapon_category, armor_category, shield_category] },
  { name: "Lightweight", effect_type: "Material", power_level: 1, description: "The object is extraordinarily light, reducing the weight by half", categories: [weapon_category, shield_category, armor_category] },
  { name: "Sharpness +1", effect_type: "Material", power_level: 1, description: "The weapon's edge is unnaturally sharp, adding +1 to attack rolls and damage", categories: [weapon_category] },
  { name: "Unyielding Defense", effect_type: "Material", power_level: 2, description: "When wielding this weapon, you gain +1 to AC", categories: [weapon_category, shield_category] },
  { name: "Swift Strike", effect_type: "Material", power_level: 3, description: "You can make one additional attack as part of your attack action 3 times per day", categories: [weapon_category] },
  { name: "Precise Strike", effect_type: "Material", power_level: 2, description: "Your critical hit range with this weapon increases by 1", categories: [weapon_category] },
  { name: "Mithril Resilience", effect_type: "Material", power_level: 1, description: "The weapon is nearly indestructible, granting resistance to any attempt to break or damage it", categories: [weapon_category] },
  { name: "Spell Channeling", effect_type: "Material", power_level: 2, description: "The weapon can be used as a focus for spellcasting, granting +1 to spell attack rolls", categories: [weapon_category, staff_category] },
  { name: "Finesse Mastery", effect_type: "Material", power_level: 3, description: "The weapon gains the Finesse property, allowing you to use Dexterity for attack and damage rolls", categories: [weapon_category] },
  { name: "Unbreakable Will", effect_type: "Material", power_level: 2, description: "While holding this weapon, you gain advantage on saving throws against being charmed or frightened", categories: [weapon_category] },
  { name: "Legendary Sharpness", effect_type: "Material", power_level: 3, description: "The weapon is so sharp it adds +3 to attack rolls and ignores non-magical resistances", categories: [weapon_category] },
  { name: "Blinding Radiance", effect_type: "Material", power_level: 1, description: "The weapon emits a faint glow, shedding dim light in a 10-foot radius", categories: [weapon_category] },
  { name: "Echo Strike", effect_type: "Material", power_level: 1, description: "After a successful hit, the weapon creates a magical echo, dealing 1 additional force damage", categories: [weapon_category] },
  { name: "Gravity Defier", effect_type: "Material", power_level: 2, description: "The weapon defies normal physics, allowing its wielder to leap an additional 5 feet horizontally or vertically", categories: [weapon_category, boots_category] },
  { name: "Phantom Reach", effect_type: "Material", power_level: 2, description: "The weapon can extend its reach by an additional 5 feet for melee attacks", categories: [weapon_category] },
  { name: "Veil of Shadows", effect_type: "Material", power_level: 3, description: "When drawn, the weapon cloaks its wielder in shadow, granting advantage on Stealth checks", categories: [weapon_category, cloak_category] },
  { name: "Mithril Ward", effect_type: "Material", power_level: 3, description: "The wielder gains resistance to slashing damage while holding this weapon", categories: [weapon_category, shield_category, armor_category] },
  { name: "Ethereal Step", effect_type: "Material", power_level: 4, description: "The weapon allows its wielder to move through non-magical obstacles as if they were ethereal", categories: [weapon_category, shield_category] },
  { name: "Elemental Infusion", effect_type: "Material", power_level: 3, description: "The weapon can be infused with elemental energy (fire, cold, lightning), dealing an extra 1d6 damage of that type", categories: [weapon_category] },
  { name: "Temporal Edge", effect_type: "Material", power_level: 3, description: "Once per day, the weapon allows its wielder to slow time briefly, gaining an extra action on their turn", categories: [weapon_category] },
  { name: "Celestial Binding", effect_type: "Material", power_level: 2, description: "The object is bound to its wielder by an unbreakable magical bond. If separated, it can be summoned back as a bonus action", categories: [weapon_category, shield_category] },

	{ name: "Ammunition Return", effect_type: "Ammunition Magic", power_level: 2, description: "The ammunition returns magically and can be used again in the next attack", categories: [ammunition_category] },

	{ name: "Damage I - Fire", effect_type: "Attack Damage", power_level: 1, description: "Adds 1d4 Fire damage", categories: [weapon_category, ammunition_category, gloves_category] },
	{ name: "Damage I - Cold", effect_type: "Attack Damage", power_level: 1,   description: "Adds 1d4 Cold damage", categories: [weapon_category, ammunition_category, gloves_category] },	
	{ name: "Damage I - Acid", effect_type: "Attack Damage", power_level: 1, description: "Adds 1d4 Acid damage", categories: [weapon_category, ammunition_category, gloves_category] },	
	{ name: "Damage I - Radiant", effect_type: "Attack Damage", power_level: 1, description: "Adds 1d4 Radiant damage", categories: [weapon_category, ammunition_category, gloves_category] },	
	{ name: "Damage I - Necrotic", effect_type: "Attack Damage", power_level: 1, description: "Adds 1d4 Necrotic damage", categories: [weapon_category, ammunition_category, gloves_category] },	
	{ name: "Damage I - Poison", effect_type: "Attack Damage", power_level: 1, description: "Adds 1d4 Poison damage", categories: [weapon_category, ammunition_category, gloves_category] },	
	{ name: "Damage I - Force", effect_type: "Attack Damage", power_level: 1, description: "Adds 1d4 Force damage", categories: [weapon_category, ammunition_category, gloves_category] },	
	{ name: "Damage I - Piercing", effect_type: "Attack Damage", power_level: 1, description: "Adds 1d4 Piercing damage", categories: [weapon_category, ammunition_category, gloves_category] },
	{ name: "Damage I - Bludgeoning", effect_type: "Attack Damage", power_level: 1, description: "Adds 1d4 Bludgeoning damage", categories: [weapon_category, ammunition_category, gloves_category] },
	{ name: "Damage I - Slashing", effect_type: "Attack Damage", power_level: 1, description: "Adds 1d4 Slashing damage", categories: [weapon_category, ammunition_category, gloves_category] },
	{ name: "Damage I - Thunder", effect_type: "Attack Damage", power_level: 1, description: "Adds 1d4 Thunder damage", categories: [weapon_category, ammunition_category, gloves_category] },
	{ name: "Damage I - Psychic", effect_type: "Attack Damage", power_level: 1, description: "Adds 1d4 Psychic damage", categories: [weapon_category, ammunition_category, gloves_category] },
	{ name: "Damage I - Lightning", effect_type: "Attack Damage", power_level: 1, description: "Adds 1d4 Lightning damage", categories: [weapon_category, ammunition_category, gloves_category] },	

	{ name: "Damage II - Fire", effect_type: "Attack Damage", power_level: 2, description: "Adds 1d6 Fire damage", categories: [weapon_category, ammunition_category] },	
	{ name: "Damage II - Cold", effect_type: "Attack Damage", power_level: 2, description: "Adds 1d6 Cold damage", categories: [weapon_category, ammunition_category] },	
	{ name: "Damage II - Acid", effect_type: "Attack Damage", power_level: 2, description: "Adds 1d6 Acid damage", categories: [weapon_category, ammunition_category] },	
	{ name: "Damage II - Radiant", effect_type: "Attack Damage", power_level: 2, description: "Adds 1d6 Radiant damage", categories: [weapon_category, ammunition_category] },	
	{ name: "Damage II - Necrotic", effect_type: "Attack Damage", power_level: 2, description: "Adds 1d6 Necrotic damage", categories: [weapon_category, ammunition_category] },	
	{ name: "Damage II - Poison", effect_type: "Attack Damage", power_level: 2, description: "Adds 1d6 Poison damage", categories: [weapon_category, ammunition_category] },	
	{ name: "Damage II - Force", effect_type: "Attack Damage", power_level: 2, description: "Adds 1d6 Force damage", categories: [weapon_category, ammunition_category] },	
	{ name: "Damage II - Piercing", effect_type: "Attack Damage", power_level: 2, description: "Adds 1d6 Piercing damage", categories: [weapon_category, ammunition_category] },
	{ name: "Damage II - Bludgeoning", effect_type: "Attack Damage", power_level: 2, description: "Adds 1d6 Bludgeoning damage", categories: [weapon_category, ammunition_category] },
	{ name: "Damage II - Slashing", effect_type: "Attack Damage", power_level: 2, description: "Adds 1d6 Slashing damage", categories: [weapon_category, ammunition_category] },
	{ name: "Damage II - Thunder", effect_type: "Attack Damage", power_level: 2, description: "Adds 1d6 Thunder damage", categories: [weapon_category, ammunition_category] },
	{ name: "Damage II - Psychic", effect_type: "Attack Damage", power_level: 2, description: "Adds 1d6 Psychic damage", categories: [weapon_category, ammunition_category] },
	{ name: "Damage II - Lightning", effect_type: "Attack Damage", power_level: 2, description: "Adds 1d6 Lightning damage", categories: [weapon_category, ammunition_category] },

	{ name: "Damage III - Fire", effect_type: "Attack Damage", power_level: 3, description: "Adds 1d8 Fire damage", categories: [weapon_category, ammunition_category] },	
	{ name: "Damage III - Cold", effect_type: "Attack Damage", power_level: 3, description: "Adds 1d8 Cold damage", categories: [weapon_category, ammunition_category] },	
	{ name: "Damage III - Acid", effect_type: "Attack Damage", power_level: 3, description: "Adds 1d8 Acid damage", categories: [weapon_category, ammunition_category] },	
	{ name: "Damage III - Radiant", effect_type: "Attack Damage", power_level: 3, description: "Adds 1d8 Radiant damage", categories: [weapon_category, ammunition_category] },	
	{ name: "Damage III - Necrotic", effect_type: "Attack Damage", power_level: 3, description: "Adds 1d8 Necrotic damage", categories: [weapon_category, ammunition_category] },	
	{ name: "Damage III - Poison", effect_type: "Attack Damage", power_level: 3, description: "Adds 1d8 Poison damage", categories: [weapon_category, ammunition_category] },	
	{ name: "Damage III - Force", effect_type: "Attack Damage", power_level: 3, description: "Adds 1d8 Force damage", categories: [weapon_category, ammunition_category] },	
	{ name: "Damage III - Piercing", effect_type: "Attack Damage", power_level: 3, description: "Adds 1d8 Piercing damage", categories: [weapon_category, ammunition_category] },
	{ name: "Damage III - Bludgeoning", effect_type: "Attack Damage", power_level: 3, description: "Adds 1d8 Bludgeoning damage", categories: [weapon_category, ammunition_category] },
	{ name: "Damage III - Slashing", effect_type: "Attack Damage", power_level: 3, description: "Adds 1d8 Slashing damage", categories: [weapon_category, ammunition_category] },
	{ name: "Damage III - Thunder", effect_type: "Attack Damage", power_level: 3, description: "Adds 1d8 Thunder damage", categories: [weapon_category, ammunition_category] },
	{ name: "Damage III - Psychic", effect_type: "Attack Damage", power_level: 3, description: "Adds 1d8 Psychic damage", categories: [weapon_category, ammunition_category] },
	{ name: "Damage III - Lightning", effect_type: "Attack Damage", power_level: 3, description: "Adds 1d8 Lightning damage", categories: [weapon_category, ammunition_category] },	
  
  { name: "Damage IV - Fire", effect_type: "Attack Damage", power_level: 4, description: "Adds 2d6 Fire damage", categories: [weapon_category] },	
	{ name: "Damage IV - Cold", effect_type: "Attack Damage", power_level: 4, description: "Adds 2d6 Cold damage", categories: [weapon_category] },	
	{ name: "Damage IV - Acid", effect_type: "Attack Damage", power_level: 4, description: "Adds 2d6 Acid damage", categories: [weapon_category] },	
	{ name: "Damage IV - Radiant", effect_type: "Attack Damage", power_level: 4, description: "Adds 2d6 Radiant damage", categories: [weapon_category] },	
	{ name: "Damage IV - Necrotic", effect_type: "Attack Damage", power_level: 4, description: "Adds 2d6 Necrotic damage", categories: [weapon_category] },	
	{ name: "Damage IV - Poison", effect_type: "Attack Damage", power_level: 4, description: "Adds 2d6 Poison damage", categories: [weapon_category] },	
	{ name: "Damage IV - Force", effect_type: "Attack Damage", power_level: 4, description: "Adds 2d6 Force damage", categories: [weapon_category] },	
	{ name: "Damage IV - Piercing", effect_type: "Attack Damage", power_level: 4, description: "Adds 2d6 Piercing damage", categories: [weapon_category] },
	{ name: "Damage IV - Bludgeoning", effect_type: "Attack Damage", power_level: 4, description: "Adds 2d6 Bludgeoning damage", categories: [weapon_category] },
	{ name: "Damage IV - Slashing", effect_type: "Attack Damage", power_level: 4, description: "Adds 2d6 Slashing damage", categories: [weapon_category] },
	{ name: "Damage IV - Thunder", effect_type: "Attack Damage", power_level: 4, description: "Adds 2d6 Thunder damage", categories: [weapon_category] },
	{ name: "Damage IV - Psychic", effect_type: "Attack Damage", power_level: 4, description: "Adds 2d6 Psychic damage", categories: [weapon_category] },
	{ name: "Damage IV - Lightning", effect_type: "Attack Damage", power_level: 4, description: "Adds 2d6 Lightning damage", categories: [weapon_category] },

	{ name: "Damage V - Fire", effect_type: "Attack Damage", power_level: 5, description: "Adds 3d6 Fire damage", categories: [weapon_category] },	
	{ name: "Damage V - Cold", effect_type: "Attack Damage", power_level: 5, description: "Adds 3d6 Cold damage", categories: [weapon_category] },	
	{ name: "Damage V - Acid", effect_type: "Attack Damage", power_level: 5, description: "Adds 3d6 Acid damage", categories: [weapon_category] },	
	{ name: "Damage V - Radiant", effect_type: "Attack Damage", power_level: 5, description: "Adds 3d6 Radiant damage", categories: [weapon_category] },	
	{ name: "Damage V - Necrotic", effect_type: "Attack Damage", power_level: 5, description: "Adds 3d6 Necrotic damage", categories: [weapon_category] },	
	{ name: "Damage V - Poison", effect_type: "Attack Damage", power_level: 5, description: "Adds 3d6 Poison damage", categories: [weapon_category] },	
	{ name: "Damage V - Force", effect_type: "Attack Damage", power_level: 5, description: "Adds 3d6 Force damage", categories: [weapon_category] },	
	{ name: "Damage V - Piercing", effect_type: "Attack Damage", power_level: 5, description: "Adds 3d6 Piercing damage", categories: [weapon_category] },
	{ name: "Damage V - Bludgeoning", effect_type: "Attack Damage", power_level: 5, description: "Adds 3d6 Bludgeoning damage", categories: [weapon_category] },
	{ name: "Damage V - Slashing", effect_type: "Attack Damage", power_level: 5, description: "Adds 3d6 Slashing damage", categories: [weapon_category] },
	{ name: "Damage V - Thunder", effect_type: "Attack Damage", power_level: 5, description: "Adds 3d6 Thunder damage", categories: [weapon_category] },
	{ name: "Damage V - Psychic", effect_type: "Attack Damage", power_level: 5, description: "Adds 3d6 Psychic damage", categories: [weapon_category] },
	{ name: "Damage V - Lightning", effect_type: "Attack Damage", power_level: 5, description: "Adds 3d6 Lightning damage", categories: [weapon_category] },

	{ name: "Flexibility", effect_type: "Flexibility", power_level: 1, description: "If an item have an attack bonus of +1 up to +5, this bonus can be used as CA for 1 turn", categories: [weapon_category, gloves_category] },
	{ name: "Frostbite", effect_type: "Frosting", power_level: 1, description: "Reduces enemy movement speed by 10 feet on a successful hit", categories: [weapon_category, ammunition_category] },
	{ name: "Electric Surge", effect_type: "Lightning", power_level: 2, description: "On command and using your bonus action, emits a jolt of electricity that deals 1d8 lightning damage to the nearest enemy", categories: [weapon_category, gloves_category] },
  { name: "Forceful Impact", effect_type: "Knocking", power_level: 2, description: "Adds a chance to knock back enemies 10 feet on a successful hit", categories: [weapon_category, gloves_category] },

  { name: "Ammunition I", effect_type: "Attack Bonus", power_level: 1, description: "This ammunition increase your attack and damage rolls add +1", categories: [ammunition_category] },
	{ name: "Ammunition II", effect_type: "Attack Bonus", power_level: 1, description: "This ammunition increase your attack and damage rolls add +2", categories: [ammunition_category] },
	{ name: "Ammunition III", effect_type: "Attack Bonus", power_level: 2, description: "This ammunition increase your attack and damage rolls add +3", categories: [ammunition_category] },
	{ name: "Ammunition IV", effect_type: "Attack Bonus", power_level: 3, description: "This ammunition increase your attack and damage rolls add +4", categories: [ammunition_category] },
	{ name: "Ammunition V", effect_type: "Attack Bonus", power_level: 4, description: "This ammunition increase your attack and damage rolls add +5", categories: [ammunition_category] },

	{ name: "Defense +1", effect_type: "Defense", power_level: 1, description: "Your armor class add +1", categories: [armor_category, amulet_category, ring_category, gem_category, gloves_category] },
	{ name: "Defense +2", effect_type: "Defense", power_level: 2, description: "Your armor class add +2", categories: [armor_category, amulet_category, ring_category, gem_category] },
	{ name: "Defense +3", effect_type: "Defense", power_level: 3, description: "Your armor class add +3", categories: [armor_category, amulet_category, ring_category, gem_category] },

	{ name: "Saving Throws I - Strength" , effect_type: "Saving Throws", power_level: 1, description: "You have a +1 to Strength Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category, gloves_category] },
	{ name: "Saving Throws I - Dexterity" , effect_type: "Saving Throws", power_level: 1, description: "You have a +1 to Dexterity Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category, gloves_category] },
	{ name: "Saving Throws I - Constitution" , effect_type: "Saving Throws", power_level: 1, description: "You have a +1 to Constitution Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category, gloves_category] },
	{ name: "Saving Throws I - Wisdom" , effect_type: "Saving Throws", power_level: 1, description: "You have a +1 to Wisdom Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category, gloves_category] },
	{ name: "Saving Throws I - Charisma" , effect_type: "Saving Throws", power_level: 1, description: "You have a +1 to Charisma Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category, gloves_category] },
	{ name: "Saving Throws I - Intelligence" , effect_type: "Saving Throws", power_level: 1, description: "You have a +1 to Intelligence Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category, gloves_category] },

	{ name: "Saving Throws II - Strength" , effect_type: "Saving Throws", power_level: 2, description: "You have a +3 to Strength Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws II - Dexterity" , effect_type: "Saving Throws", power_level: 2, description: "You have a +3 to Dexterity Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws II - Constitution" , effect_type: "Saving Throws", power_level: 2, description: "You have a +3 to Constitution Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws II - Wisdom" , effect_type: "Saving Throws", power_level: 2, description: "You have a +3 to Wisdom Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws II - Charisma" , effect_type: "Saving Throws", power_level: 2, description: "You have a +3 to Charisma Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws II - Intelligence" , effect_type: "Saving Throws", power_level: 2, description: "You have a +3 to Intelligence Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },

	{ name: "Saving Throws III - Strength" , effect_type: "Saving Throws", power_level: 3, description: "You have a +5 to Strength Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws III - Dexterity" , effect_type: "Saving Throws", power_level: 3, description: "You have a +5 to Dexterity Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws III - Constitution" , effect_type: "Saving Throws", power_level: 3, description: "You have a +5 to Constitution Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws III - Wisdom" , effect_type: "Saving Throws", power_level: 3, description: "You have a +5 to Wisdom Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws III - Charisma" , effect_type: "Saving Throws", power_level: 3, description: "You have a +5 to Charisma Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws III - Intelligence" , effect_type: "Saving Throws", power_level: 3, description: "You have a +5 to Intelligence Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },

	{ name: "Saving Throws IV - Strength" , effect_type: "Saving Throws", power_level: 3, description: "You have advantage on Strength Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws IV - Dexterity" , effect_type: "Saving Throws", power_level: 3, description: "You have advantage on Dexterity Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws IV - Constitution" , effect_type: "Saving Throws", power_level: 3, description: "You advantage on to Constitution Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws IV - Wisdom" , effect_type: "Saving Throws", power_level: 3, description: "You advantage on to Wisdom Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws IV - Charisma" , effect_type: "Saving Throws", power_level: 3, description: "You have advantage on Charisma Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws IV - Intelligence" , effect_type: "Saving Throws", power_level: 3, description: "You have advantage on Intelligence Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },

	{ name: "Saving Throws V - All" , effect_type: "Saving Throws", power_level: 2, description: "You have a +1 to all Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws VI - All" , effect_type: "Saving Throws", power_level: 3, description: "You have a +2 to all Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws VII - All" , effect_type: "Saving Throws", power_level: 4, description: "You have a +3 to all Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws VIII - All" , effect_type: "Saving Throws", power_level: 5, description: "You have a +5 to all Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws IX - All" , effect_type: "Saving Throws", power_level: 5, description: "You advantage to all Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },

	{ name: "Saving Throws V - Fisical" , effect_type: "Saving Throws", power_level: 2, description: "You have a +1 to Strength, Dexterity and Constitution Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws VI - Fisical" , effect_type: "Saving Throws", power_level: 2, description: "You have a +2 to Strength, Dexterity and Constitution Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws VII - Fisical" , effect_type: "Saving Throws", power_level: 3, description: "You have a +3 to Strength, Dexterity and Constitution Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws VIII - Fisical" , effect_type: "Saving Throws", power_level: 4, description: "You have a +5 to Strength, Dexterity and Constitution Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws IX - Fisical" , effect_type: "Saving Throws", power_level: 4, description: "You advantage on Strength, Dexterity and Constitution Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },

	{ name: "Saving Throws V - Magical" , effect_type: "Saving Throws", power_level: 2, description: "You have a +1 to Wisdom, Charisma and Intelligence Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws VI - Magical" , effect_type: "Saving Throws", power_level: 3, description: "You have a +2 to Wisdom, Charisma and Intelligence Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws VII - Magical" , effect_type: "Saving Throws", power_level: 3, description: "You have a +3 Wisdom, Charisma and Intelligence Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws VIII - Magical" , effect_type: "Saving Throws", power_level: 4, description: "You have a +5 Wisdom, Charisma and Intelligence Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },
	{ name: "Saving Throws IX - Magical" , effect_type: "Saving Throws", power_level: 4, description: "You advantage on Wisdom, Charisma and Intelligence Saving Throws", categories: [armor_category, amulet_category, ring_category, gem_category, shield_category] },

	{ name: "Ignores Dexterity Penalty", effect_type: "Defense", power_level: 2, description: "Ignore Dexterity restrictions for armors", categories: [armor_category, shield_category] },
	{ name: "Ignores Stealth Penalty", effect_type: "Defense", power_level: 2, description: "Ignore Stealth restrictions for armors", categories: [armor_category, shield_category] },
	
	{ name: "Resistance - Fire", effect_type: "Resistance", power_level: 1, description: "Provides resistance to Fire damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category, gloves_category] },	
	{ name: "Resistance - Cold", effect_type: "Resistance", power_level: 1, description: "Provides resistance to  Cold damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category, gloves_category] },	
	{ name: "Resistance - Acid", effect_type: "Resistance", power_level: 1, description: "Provides resistance to Acid damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category, gloves_category] },	
	{ name: "Resistance - Radiant", effect_type: "Resistance", power_level: 1, description: "Provides resistance to Radiant damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category, gloves_category] },	
	{ name: "Resistance - Necrotic", effect_type: "Resistance", power_level: 1, description: "Provides resistance to Necrotic damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category, gloves_category] },	
	{ name: "Resistance - Poison", effect_type: "Resistance", power_level: 1, description: "Provides resistance to Poison damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category, gloves_category] },	
	{ name: "Resistance - Force", effect_type: "Resistance", power_level: 1, description: "Provides resistance to Force damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category, gloves_category] },	
	{ name: "Resistance - Piercing", effect_type: "Resistance", power_level: 1, description: "Provides resistance to Piercing damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category, gloves_category] },
	{ name: "Resistance - Bludgeoning", effect_type: "Resistance", power_level: 1, description: "Provides resistance to Bludgeoning damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category, gloves_category] },
	{ name: "Resistance - Slashing", effect_type: "Resistance", power_level: 1, description: "Provides resistance to Slashing damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category, gloves_category] },
	{ name: "Resistance - Thunder", effect_type: "Resistance", power_level: 1, description: "Provides resistance to Thunder damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category, gloves_category] },
	{ name: "Resistance - Psychic", effect_type: "Resistance", power_level: 1, description: "Provides resistance to Psychic damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category, gloves_category] },
	{ name: "Resistance - Lightning", effect_type: "Resistance", power_level: 1, description: "Provides resistance to Lightning damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category, gloves_category] },

  { name: "Stone Skin", effect_type: "Resistance", power_level: 4, description: "Temporarily grants resistance to bludgeoning, piercing, and slashing damage from non-magical attacks", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category] },	
	
	{ name: "Inmunity - Fire", effect_type: "Inmunity", power_level: 3, description: "Provides inmunity to Fire damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category] },
	{ name: "Inmunity - Cold", effect_type: "Inmunity", power_level: 3, description: "Provides inmunity to  Cold damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category] },	
	{ name: "Inmunity - Acid", effect_type: "Inmunity", power_level: 3, description: "Provides inmunity to Acid damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category] },	
	{ name: "Inmunity - Radiant", effect_type: "Inmunity", power_level: 3, description: "Provides inmunity to Radiant damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category] },	
	{ name: "Inmunity - Necrotic", effect_type: "Inmunity", power_level: 3, description: "Provides inmunity to Necrotic damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category] },	
	{ name: "Inmunity - Poison", effect_type: "Inmunity", power_level: 3, description: "Provides inmunity to Poison damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category] },	
	{ name: "Inmunity - Force", effect_type: "Inmunity", power_level: 3, description: "Provides inmunity to Force damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category] },	
	{ name: "Inmunity - Piercing", effect_type: "Inmunity", power_level: 3, description: "Provides inmunity to Piercing damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category] },
	{ name: "Inmunity - Bludgeoning", effect_type: "Inmunity", power_level: 3, description: "Provides inmunity to Bludgeoning damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category] },
	{ name: "Inmunity - Slashing", effect_type: "Inmunity", power_level: 3, description: "Provides inmunity to Slashing damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category] },
	{ name: "Inmunity - Thunder", effect_type: "Inmunity", power_level: 3, description: "Provides inmunity to Thunder damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category] },
	{ name: "Inmunity - Psychic", effect_type: "Inmunity", power_level: 3, description: "Provides inmunity to Psychic damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category] },
	{ name: "Inmunity - Lightning", effect_type: "Inmunity", power_level: 3, description: "Provides inmunity to Lightning damage", categories: [armor_category, shield_category, amulet_category, ring_category, gem_category] },

  { name: "Water Breathing", effect_type: "Utility", power_level: 2, description: "Grants the ability to breathe underwater for 1 hour", categories: [amulet_category, ring_category, gem_category] },
  { name: "Shield of Light", effect_type: "Protection", power_level: 3, description: "Creates a radiant shield that grants +1 AC for 10 minutes" , categories: [shield_category, amulet_category, ring_category, gem_category, wands_category] },
  { name: "Phantom Step", effect_type: "Stealth", power_level: 2, description: "Allows the user to move silently for 1 hour, granting advantage on stealth checks", categories: [amulet_category, ring_category, gem_category] },
  { name: "Wind Walk", effect_type: "Movement", power_level: 1, description: "Increases movement speed by 10 feet for 1 minute", categories: [boots_category, amulet_category, ring_category, gem_category] },
  { name: "Arcane Sight", effect_type: "Detection", power_level: 1, description: "Allows the user to detect magic within a 30-foot radius for 10 minutes", categories: [boots_category, amulet_category, ring_category, gem_category, wands_category] },
  { name: "Feather Fall", effect_type: "Protection", power_level: 1, description: "Slows the user's descent, preventing fall damage from heights under 100 feet", categories: [boots_category, amulet_category, ring_category, gem_category, wands_category] },
  
  { name: "Blazing Speed I", effect_type: "Initiative", power_level: 1, description: "Provides a +1 bonus to initiative rolls", categories: [amulet_category, ring_category, gem_category, armor_category, weapon_category, gloves_category, gloves_category] },
  { name: "Blazing Speed II", effect_type: "Initiative", power_level: 2, description: "Provides a +3 bonus to initiative rolls", categories: [amulet_category, ring_category, gem_category, armor_category, weapon_category, gloves_category, gloves_category] },
  { name: "Blazing Speed III", effect_type: "Initiative", power_level: 3, description: "Provides a +5 bonus to initiative rolls", categories: [amulet_category, ring_category, gem_category, armor_category, weapon_category] },
  { name: "Blazing Speed V", effect_type: "Initiative", power_level: 3, description: "Provides advantage to initiative rolls", categories: [amulet_category, ring_category, gem_category, armor_category, weapon_category] },
 
  { name: "Mana Infusion", effect_type: "Restoration", power_level: 3, description: "Restores a low-level spell slot once per long rest", categories: [amulet_category, ring_category, gem_category, gloves_category] },
  { name: "Spectral Hand", effect_type: "Utility", power_level: 1, description: "Allows the user to reach and manipulate objects up to 15 feet away as if using an invisible hand", categories: [amulet_category, ring_category, gem_category, gloves_category] },
  { name: "Radiant Burst", effect_type: "Control", power_level: 4, description: "Emits a flash of light that blinds nearby enemies for one turn", categories: [amulet_category, ring_category, gem_category, gloves_category] },
  { name: "Poison Cloud", effect_type: "Attack", power_level: 3, description: "Releases a small cloud of poison gas that lingers for 1 minute, dealing poison damage to anyone inside", categories: [amulet_category, ring_category, gem_category] },
  { name: "Healing Aura", effect_type: "Restoration", power_level: 2, description: "Provides a regenerative effect that restores 1 HP per turn for 5 turns", categories: [amulet_category, ring_category, gem_category] },
  
  { name: "Shadow Veil", effect_type: "Stealth", power_level: 3, description: "Cloaks the user in shadows, granting advantage on stealth checks in dim light or darkness", categories: [cloak_category] },
  { name: "Cloak of Mists", effect_type: "Protection", power_level: 3, description: "Creates a misty shroud around the user, giving enemies disadvantage on attack rolls for 1 minute", categories: [cloak_category] },
  { name: "Cloak of Change", effect_type: "Utility", power_level: 1, description: "This item can change style, color and quality", categories: [cloak_category, gloves_category] },

  { name: "Ability Improve I - Strength", effect_type: "Enhance", power_level: 1, description: "Provides +1 to Strength", categories: [amulet_category, ring_category, gem_category, gloves_category] },
  { name: "Ability Improve I - Dexterity", effect_type: "Enhance", power_level: 1, description: "Provides +1 to Dexterity", categories: [amulet_category, ring_category, gem_category, gloves_category] },
  { name: "Ability Improve I - Constitution", effect_type: "Enhance", power_level: 1, description: "Provides +1 to Constitution", categories: [amulet_category, ring_category, gem_category, gloves_category] },
  { name: "Ability Improve I - Wisdom", effect_type: "Enhance", power_level: 1, description: "Provides +1 to Wisdom", categories: [amulet_category, ring_category, gem_category, gloves_category] },
  { name: "Ability Improve I - Intelligence", effect_type: "Enhance", power_level: 1, description: "Provides +1 to Intelligence", categories: [amulet_category, ring_category, gem_category, gloves_category] },
  { name: "Ability Improve I - Charisma", effect_type: "Enhance", power_level: 1, description: "Provides +1 to Charisma", categories: [amulet_category, ring_category, gem_category, gloves_category] },

  { name: "Ability Improve II - Strength", effect_type: "Enhance", power_level: 2, description: "Provides +2 to Strength", categories: [amulet_category, ring_category, gem_category] },
  { name: "Ability Improve II - Dexterity", effect_type: "Enhance", power_level: 2, description: "Provides +2 to Dexterity", categories: [amulet_category, ring_category, gem_category] },
  { name: "Ability Improve II - Constitution", effect_type: "Enhance", power_level: 2, description: "Provides +2 to Constitution", categories: [amulet_category, ring_category, gem_category] },
  { name: "Ability Improve II - Wisdom", effect_type: "Enhance", power_level: 2, description: "Provides +2 to Wisdom", categories: [amulet_category, ring_category, gem_category] },
  { name: "Ability Improve II - Intelligence", effect_type: "Enhance", power_level: 2, description: "Provides +2 to Intelligence", categories: [amulet_category, ring_category, gem_category] },
  { name: "Ability Improve II - Charisma", effect_type: "Enhance", power_level: 2, description: "Provides +2 to Charisma", categories: [amulet_category, ring_category, gem_category] },

  { name: "Ability Improve III - Strength", effect_type: "Enhance", power_level: 3, description: "Provides +3 to Strength", categories: [amulet_category, ring_category, gem_category] },
  { name: "Ability Improve III - Dexterity", effect_type: "Enhance", power_level: 3, description: "Provides +3 to Dexterity", categories: [amulet_category, ring_category, gem_category] },
  { name: "Ability Improve III - Constitution", effect_type: "Enhance", power_level: 3, description: "Provides +3 to Constitution", categories: [amulet_category, ring_category, gem_category] },
  { name: "Ability Improve III - Wisdom", effect_type: "Enhance", power_level: 3, description: "Provides +3 to Wisdom", categories: [amulet_category, ring_category, gem_category] },
  { name: "Ability Improve III - Intelligence", effect_type: "Enhance", power_level: 3, description: "Provides +3 to Intelligence", categories: [amulet_category, ring_category, gem_category] },
  { name: "Ability Improve III - Charisma", effect_type: "Enhance", power_level: 3, description: "Provides +3 to Charisma", categories: [amulet_category, ring_category, gem_category] },

  { name: "Ability Advantage - Strength", effect_type: "Enhance", power_level: 2, description: "Provides advantage on Strength saving throws", categories: [amulet_category, ring_category, gem_category] },
  { name: "Ability Advantage - Dexterity", effect_type: "Enhance", power_level: 2, description: "Provides advantage on Dexterity saving throws", categories: [amulet_category, ring_category, gem_category] },
  { name: "Ability Advantage - Constitution", effect_type: "Enhance", power_level: 2, description: "Provides +advantage on Constitution saving throws", categories: [amulet_category, ring_category, gem_category] },
  { name: "Ability Advantage - Wisdom", effect_type: "Enhance", power_level: 2, description: "Provides advantage on Wisdom saving throws", categories: [amulet_category, ring_category, gem_category] },
  { name: "Ability Advantage - Intelligence", effect_type: "Enhance", power_level: 2, description: "Provides advantage on Intelligence saving throws", categories: [amulet_category, ring_category, gem_category] },
  { name: "Ability Advantage - Charisma", effect_type: "Enhance", power_level: 2, description: "Provides advantage on Charisma saving throws", categories: [amulet_category, ring_category, gem_category] },

  { name: "Combat Speed", effect_type: "Enhance", power_level: 3, description: "Grant the effect of the haste spell on self for 1 min each day", categories: [boots_category, amulet_category, ring_category, gem_category] },
  { name: "Combat Size", effect_type: "Enhance", power_level: 3, description: "Grant the effect of the enlarge/reduce spell on self for 10 min each day", categories: [amulet_category, ring_category, gem_category] },
  { name: "Combat Awarness", effect_type: "Enhance", power_level: 2, description: "You cannot be surprised and have a +2 to initiative rolls", categories: [amulet_category, ring_category, gem_category] },

  { name: "False Tracks", effect_type: "Traces", power_level: 1, description: "Leave traces of another type of humanoid of the same size", categories: [boots_category, amulet_category, ring_category, gem_category] },
  { name: "Back Tracks", effect_type: "Traces", power_level: 1, description: "Leave traces going to the opposite way", categories: [boots_category, amulet_category, ring_category, gem_category] },

	{ name: "Magical Absortion I", effect_type: "Absortion", power_level: 1, description: "You can store any cantrip or spell level 1", categories: [weapon_category, armor_category, cloak_category, amulet_category, ring_category, gem_category, wands_category] },
	{ name: "Magical Absortion II", effect_type: "Absortion", power_level: 1, description: "You can store any cantrip or spell level 2", categories: [weapon_category, armor_category, cloak_category, amulet_category, ring_category, gem_category, wands_category] },
	{ name: "Magical Absortion III", effect_type: "Absortion", power_level: 2, description: "You can store any cantrip or spell level 3", categories: [weapon_category, armor_category, cloak_category, amulet_category, ring_category, gem_category, wands_category] },
	{ name: "Magical Absortion IV", effect_type: "Absortion", power_level: 2, description: "You can store any cantrip or spell level 4", categories: [weapon_category, armor_category, cloak_category, amulet_category, ring_category, gem_category, wands_category] },
	{ name: "Magical Absortion V", effect_type: "Absortion", power_level: 3, description: "You can store any cantrip or spell up to 5 levels", categories: [cloak_category, amulet_category, ring_category, gem_category, wands_category] },
	{ name: "Magical Absortion VI", effect_type: "Absortion", power_level: 3, description: "You can store any cantrip or spell up to 6 levels", categories: [cloak_category, amulet_category, ring_category, gem_category, wands_category] },
	{ name: "Magical Absortion VII", effect_type: "Absortion", power_level: 4, description: "You can store any cantrip or spell up to 7 levels", categories: [cloak_category, amulet_category, ring_category, gem_category, wands_category] },
	{ name: "Magical Absortion VII", effect_type: "Absortion", power_level: 4, description: "You can store any cantrip or spell up to 8 levels", categories: [cloak_category, amulet_category, ring_category, gem_category, wands_category] },
	{ name: "Magical Absortion IX", effect_type: "Absortion", power_level: 5, description: "You can store any cantrip or spell up to 9 levels", categories: [cloak_category, amulet_category, ring_category, gem_category, wands_category] },
	{ name: "Magical Absortion X", effect_type: "Absortion", power_level: 5, description: "You can store any cantrip or spell up to 10 levels", categories: [cloak_category, amulet_category, ring_category, gem_category, wands_category] },

	{ name: "Always Clean", effect_type: "Utility", power_level: 1, description: "This armor never gets dirty", categories: [cloak_category, armor_category] },
	{ name: "Critical Defense", effect_type: "Utility", power_level: 2, description: "This armor converts any critical hit into a normal hit", categories: [cloak_category, armor_category] },
	
  { name: "Always Burning", effect_type: "Eternity", power_level: 1, description: "This candle is not extinguished when immersed in water", categories: [trinkets_category] },
  { name: "Always On Side", effect_type: "Luck", power_level: 1, description: "This six-sided die allows you to control the result", categories: [trinkets_category] },
  { name: "Eye of Replace", effect_type: "Seeing", power_level: 1, description: "This artificial eye replaces a real one that was lost or removed", categories: [trinkets_category] },
  { name: "Magical Lock", effect_type: "Locking", power_level: 1, description: "This magical lock imposes disadvantage to pick the lock", categories: [trinkets_category] },
  { name: "Fishig Pole", effect_type: "Fishing", power_level: 1, description: "This pole transforms into a complete fishing pole", categories: [trinkets_category] },
  { name: "Weird Doll", effect_type: "Weirdness", power_level: 1, description: "This doll can speak up to six sentences when in conditions you specified", categories: [trinkets_category] },
  { name: "Never Drunk", effect_type: "Sobriety", power_level: 1, description: "This tankard allows you to drink alcohol without getting drunk", categories: [trinkets_category] },
  { name: "Robber Dreams", effect_type: "Stealing", power_level: 1, description: "Grant a +5 bonus to Dexterity (Sleight of Hand) checks and Dexterity checks to pick locks", categories: [gloves_category, trinkets_category] },
  
	{ name: "Swim Master", effect_type: "Movement", power_level: 1, description: "Grant a swimming speed equal to your walking speed", categories: [amulet_category, ring_category, gem_category, gloves_category, trinkets_category] },
	{ name: "Communication Stones", effect_type: "Understanding", power_level: 1, description: "Cast sending with the bearer of the other stone", categories: [amulet_category, ring_category, gem_category, trinkets_category] },
	{ name: "Comprehend Languages", effect_type: "Understanding", power_level: 1, description: "Cast the comprehend languages at will", categories: [amulet_category, ring_category, gem_category, trinkets_category] },
	{ name: "Freedom of Move", effect_type: "Movement", power_level: 1, description: "Grant the effect of the freedom of movement", categories: [amulet_category, ring_category, gem_category, trinkets_category, boots_category] },
	{ name: "Walk on Water", effect_type: "Movement", power_level: 1, description: "Allow to stand on and move across any liquid surface for 1 hour", categories: [amulet_category, ring_category, gem_category, trinkets_category, boots_category] },
	{ name: "Jump High", effect_type: "Jumping", power_level: 1, description: "Cast jump but only for yourself", categories: [amulet_category, ring_category, gem_category, trinkets_category, boots_category] },

	{ name: "Mind Protection", effect_type: "Minding", power_level: 1, description: "Immune to magic that allows other creatures to read your thoughts", categories: [amulet_category, ring_category, gem_category, trinkets_category] },
	{ name: "Aquatic", effect_type: "Water", power_level: 1, description: "Allows the wielder to breathe underwater and suffers no penalty to attacks in water", categories: [amulet_category, ring_category, gem_category, trinkets_category] },
	{ name: "Assassin", effect_type: "Assassination", power_level: 1, description: "You deal extra damage with this weapon if you surprise the opponent", categories: [amulet_category, ring_category, gem_category, trinkets_category, weapon_category] },
	{ name: "Summonable", effect_type: "Summoning", power_level: 1, description: "Once attuned the wielder can summon the weapon to their hand, if it is within 300 ft. of the wielder", categories: [weapon_category] },
	{ name: "Cleaving", effect_type: "Cleaving", power_level: 1, description: "Double damage when used against inanimate objects", categories: [weapon_category, gloves_category, ammunition_category] },
	{ name: "Goliath Killer", effect_type: "Goliath", power_level: 1, description: "This weapon deals 1d6 bonus damage to a targeted creature if they’re bigger than the wielder", categories: [weapon_category, gloves_category, ammunition_category] },
  { name: "Handling", effect_type: "Handling", power_level: 1, description: "This weapon ‘glues’ itself to your hand. You can never be disarmed while using this weapon", categories: [weapon_category, gloves_category, ammunition_category] },	
	{ name: "Homing", effect_type: "Sense", power_level: 1, description: "When separated from the weapon, the owner will have a sense of where it is", categories: [weapon_category] },
	{ name: "Incorruptible", effect_type: "Durability", power_level: 1, description: "The blade is self-cleaning and self-sharpening. It is immune to rust monsters and dispel magic", categories: [weapon_category] },
  { name: "Indestructible", effect_type: "Durability", power_level: 1, description: "No matter how much damage this weapon endures, it will always reform within 12 hours", categories: [weapon_category] },
  { name: "Morality", effect_type: "Morality", power_level: 1, description: "You can cast Detect Good and Evil up to 3 times a day while holding this weapon", categories: [weapon_category, gloves_category] },
  { name: "Paralyzing", effect_type: "Paralyzing", power_level: 1, description: "Once per long rest, this weapon can inflict paralysis on a successful hit", categories: [weapon_category] },
  { name: "Precise", effect_type: "Precision", power_level: 2, description: "This weapon scores a critical hit on a natural 19 or 20", categories: [weapon_category, gloves_category] },
  { name: "Reach", effect_type: "Reach", power_level: 1, description: "3 times per day, you can double the range of this weapon", categories: [weapon_category, gloves_category] },
	{ name: "Range Master I", effect_type: "Precision", power_level: 1, description: "+2 to damage rolls on ranged attacks made with longbow or shortbow", categories: [gloves_category] },
	{ name: "Range Master II", effect_type: "Precision", power_level: 1, description: "+2 to attacks rolls on ranged attacks made with longbow or shortbow", categories: [gloves_category] },

	{ name: "Potion of Rejuvenation", effect_type: "Healing", power_level: 1, description: "Your physical age is reduced by 1d6 + 6 years", categories: [potions_category] },
	{ name: "Potion of Vitality", effect_type: "Healing", power_level: 1, description: "Remove exhaustion and cure any disease or poison. You regain the maximum hp for any Hit Die you spend during 24 h", categories: [potions_category] },
	{ name: "Potion of Seen", effect_type: "Vision", power_level: 1, description: "Grant the effect of the clairvoyance spell", categories: [potions_category] },
	{ name: "Potion of Change", effect_type: "Enlarge", power_level: 1, description: "Grant the effect of the enlarge/reduce spell for 1 hour", categories: [potions_category] },
	{ name: "Potion of Life", effect_type: "Healing", power_level: 1, description: "Give 10 temporary hp and you're under the effect of the bless spell for 1 hour", categories: [potions_category] },
	{ name: "Potion of Gas", effect_type: "Change", power_level: 1, description: "Grant the effect of the gaseous form spell for 1 hour", categories: [potions_category] },
	{ name: "Potion of Resistance", effect_type: "Resistance", power_level: 1, description: "Grant resistance to all damage for 1 min", categories: [potions_category] },
	{ name: "Potion of Mind Reading", effect_type: "Minding", power_level: 1, description: "Grant the effect of the detect thoughts spell", categories: [potions_category] },
	{ name: "Potion of Night Vision", effect_type: "Vision", power_level: 1, description: "Grants the ability to see in darkness up to 60 feet for 1 hour", categories: [potions_category] },
	{ name: "Potion of Giant's Strength", effect_type: "Stength", power_level: 3, description: "Increases your Strength to 21 for 1 hour", categories: [potions_category] },
	{ name: "Potion of Water Breathing", effect_type: "Breathing", power_level: 2, description: "Allows you to breathe underwater for 1 hour", categories: [potions_category] },
	{ name: "Potion of Speed", effect_type: "Speed", power_level: 3, description: "Doubles your movement speed and grants an extra action per turn for 1 minute", categories: [potions_category] },
	{ name: "Potion of Fire Resistance", effect_type: "Resistance", power_level: 2, description: "Grants resistance to fire damage for 1 hour", categories: [potions_category] },
	{ name: "Potion of True Sight", effect_type: "Sight", power_level: 2, description: "Grants the ability to see invisible creatures and objects, and see into the Ethereal Plane for 1 hour", categories: [potions_category] },
	{ name: "Potion of Healing", effect_type: "Healing", power_level: 1, description: "Restores 2d4 + 2 hit points", categories: [potions_category] },
	{ name: "Potion of Flight", effect_type: "Flight", power_level: 3, description: "Grants a flying speed equal to your walking speed for 10 minutes", categories: [potions_category] },
	{ name: "Potion of Invisibility", effect_type: "Stealth", power_level: 2, description: "Grants invisibility for 1 hour, ending if you attack or cast a spell", categories: [potions_category] },
	{ name: "Potion of Vitality", effect_type: "Healing", power_level: 2, description: "Removes all exhaustion, cures any disease or poison, and restores maximum hit points for 24 hours", categories: [potions_category] },

	{ name: "Climbing Speed", effect_type: "Climbing", power_level: 2, description: "Grant a climbing speed equal to your walking speed for 1 hour", categories: [boots_category, cloak_category, trinkets_category] },
	{ name: "Power Knockback", effect_type: "Proning", power_level: 3, description: "This attack requires a Strength saving throw or be knocked prone", categories: [ammunition_category, weapon_category] },
	{ name: "Saddle of Secure Riding", effect_type: "Equilibrium", power_level: 2, description: "This saddle prevents you from falling off your horse against your will", categories: [trinkets_category] },
	{ name: "Ring of Invisibility", effect_type: "Stealth", power_level: 3, description: "You become invisible until the ring is removed, or you attack or cast a spell", categories: [ring_category] },
	{ name: "Naked Bonus", effect_type: "Defensive", power_level: 4, description: "+2 bonus to AC without armor nor shield", categories: [ring_category, amulet_category] },

	{ name: "Breathing Cap", effect_type: "Breathing", power_level: 3, description: "This cap allows you to breathe normally underwater", categories: [helm_category, trinkets_category, cloak_category] },
	{ name: "Horn of Hearing", effect_type: "Loudness", power_level: 2, description: "This horn suppresses the effects of the deafened condition on you", categories: [trinkets_category] },
	{ name: "Traveler's Clothes Repair", effect_type: "Durability", power_level: 1, description: "This outfit of traveler's clothes magically mends itself to counteract daily wear and tear", categories: [cloak_category, boots_category, trinkets_category] },
	{ name: "Glowing Eyes Helm", effect_type: "Glow", power_level: 2, description: "This fearsome steel helm makes your eyes glow red", categories: [helm_category, armor_category, trinkets_category] },
])
